DROP TABLE IF EXISTS `tax_offices`;

CREATE TABLE `tax_offices` (
  `id` int NOT NULL AUTO_INCREMENT,
  `plate_code` varchar(155) DEFAULT NULL,
  `city` varchar(155) DEFAULT NULL,
  `district` varchar(155) DEFAULT NULL,
  `name` varchar(155) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2080 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


LOCK TABLES `tax_offices` WRITE;

INSERT INTO `tax_offices` VALUES 
(1,'01','Adana','FEKE','FEKE MAL MÜDÜRLÜĞÜ'),
(2,'01','Adana','KARAİSALI','KARAİSALI MAL MÜDÜRLÜĞÜ'),
(3,'01','Adana','POZANTI','POZANTI MAL MÜDÜRLÜĞÜ'),
(4,'01','Adana','SAİMBEYLİ','SAİMBEYLİ MAL MÜDÜRLÜĞÜ'),
(5,'01','Adana','TUFANBEYLİ','TUFANBEYLİ MAL MÜDÜRLÜĞÜ'),
(6,'01','Adana','YUMURTALIK','YUMURTALIK MAL MÜDÜRLÜĞÜ'),
(7,'01','Adana','ALADAĞ','ALADAĞ MAL MÜDÜRLÜĞÜ'),
(8,'01','Adana','İMAMOĞLU','İMAMOĞLU MAL MÜDÜRLÜĞÜ'),
(9,'01','Adana','CEYHAN','CEYHAN VERGİ DAİRESİ'),
(10,'01','Adana','KOZAN','KOZAN VERGİ DAİRESİ'),
(11,'01','Adana','KARATAŞ','KARATAŞ VERGİ DAİRESİ'),
(12,'01','Adana','YÜREĞİR','ADANA İHTİSAS VERGİ DAİRESİ'),
(13,'01','Adana','SEYHAN','5OCAK VERGİ DAİRESİ'),
(14,'01','Adana','YÜREĞİR','YÜREĞİR VERGİ DAİRESİ'),
(15,'01','Adana','SEYHAN','SEYHAN VERGİ DAİRESİ'),
(16,'01','Adana','YÜREĞİR','ZİYAPAŞA VERGİ DAİRESİ'),
(17,'01','Adana','ÇUKUROVA','ÇUKUROVA VERGİ DAİRESİ'),
(18,'02','Adıyaman','BESNİ','BESNİ MAL MÜDÜRLÜĞÜ'),
(19,'02','Adıyaman','ÇELİKHAN','ÇELİKHAN MAL MÜDÜRLÜĞÜ'),
(20,'02','Adıyaman','GERGER','GERGER MAL MÜDÜRLÜĞÜ'),
(21,'02','Adıyaman','GÖLBAŞI','GÖLBAŞI MAL MÜDÜRLÜĞÜ'),
(22,'02','Adıyaman','SAMSAT','SAMSAT MAL MÜDÜRLÜĞÜ'),
(23,'02','Adıyaman','SİNCİK','SİNCİK MAL MÜDÜRLÜĞÜ'),
(24,'02','Adıyaman','TUT','TUT MAL MÜDÜRLÜĞÜ'),
(25,'02','Adıyaman','ADIYAMAN MERKEZ','ADIYAMAN VERGİ DAİRESİ'),
(26,'02','Adıyaman','KAHTA','KAHTA VERGİ DAİRESİ'),
(27,'03','Afyon','DAZKIRI','DAZKIRI MAL MÜDÜRLÜĞÜ'),
(28,'03','Afyon','İHSANİYE','İHSANİYE MAL MÜDÜRLÜĞÜ'),
(29,'03','Afyon','SİNANPAŞA','SİNANPAŞA MAL MÜDÜRLÜĞÜ'),
(30,'03','Afyon','SULTANDAĞI','SULTANDAĞI MAL MÜDÜRLÜĞÜ'),
(31,'03','Afyon','ŞUHUT','ŞUHUT MAL MÜDÜRLÜĞÜ'),
(32,'03','Afyon','BAŞMAKÇI','BAŞMAKÇI MAL MÜDÜRLÜĞÜ'),
(33,'03','Afyon','BAYAT','BAYAT MAL MÜDÜRLÜĞÜ'),
(34,'03','Afyon','ÇOBANLAR','ÇOBANLAR MAL MÜDÜRLÜĞÜ'),
(35,'03','Afyon','EVCİLER','EVCİLER MAL MÜDÜRLÜĞÜ'),
(36,'03','Afyon','HOCALAR','HOCALAR MAL MÜDÜRLÜĞÜ'),
(37,'03','Afyon','KIZILÖREN','KIZILÖREN MAL MÜDÜRLÜĞÜ'),
(38,'03','Afyon','AFYONKARAHİSAR MERKEZ','TINAZTEPE VERGİ DAİRESİ'),
(39,'03','Afyon','ÇAY','ÇAY VERGİ DAİRESİ'),
(40,'03','Afyon','DİNAR','DİNAR VERGİ DAİRESİ'),
(41,'03','Afyon','BOLVADİN','BOLVADİN VERGİ DAİRESİ'),
(42,'03','Afyon','EMİRDAĞ','EMİRDAĞ VERGİ DAİRESİ'),
(43,'03','Afyon','SANDIKLI','SANDIKLI VERGİ DAİRESİ'),
(44,'03','Afyon','İSCEHİSAR','İSCEHİSAR VERGİ DAİRESİ'),
(45,'03','Afyon','AFYONKARAHİSAR MERKEZ','KOCATEPE VERGİ DAİRESİ'),
(46,'04','Ağrı','DİYADİN','DİYADİN MAL MÜDÜRLÜĞÜ'),
(47,'04','Ağrı','ELEŞKİRT','ELEŞKİRT MAL MÜDÜRLÜĞÜ'),
(48,'04','Ağrı','HAMUR','HAMUR MAL MÜDÜRLÜĞÜ'),
(49,'04','Ağrı','TAŞLIÇAY','TAŞLIÇAY MAL MÜDÜRLÜĞÜ'),
(50,'04','Ağrı','TUTAK','TUTAK MAL MÜDÜRLÜĞÜ'),
(51,'04','Ağrı','AĞRI MERKEZ','AĞRI VERGİ DAİRESİ'),
(52,'04','Ağrı','DOĞUBAYAZIT','DOĞUBEYAZIT VERGİ DAİRESİ'),
(53,'04','Ağrı','PATNOS','PATNOS VERGİ DAİRESİ'),
(54,'05','Amasya','GÖYNÜCEK','GÖYNÜCEK MAL MÜDÜRLÜĞÜ'),
(55,'05','Amasya','HAMAMÖZÜ','HAMAMÖZÜ MAL MÜDÜRLÜĞÜ'),
(56,'05','Amasya','AMASYA MERKEZ','AMASYA VERGİ DAİRESİ'),
(57,'05','Amasya','MERZİFON','MERZİFON VERGİ DAİRESİ'),
(58,'05','Amasya','GÜMÜŞHACIKÖY','G. HACIKÖY VERGİ DAİRESİ'),
(59,'05','Amasya','TAŞOVA','TAŞOVA VERGİ DAİRESİ'),
(60,'05','Amasya','SULUOVA','SULUOVA VERGİ DAİRESİ'),
(61,'06','Ankara','AYAŞ','AYAŞ MAL MÜDÜRLÜĞÜ'),
(62,'06','Ankara','BALA','BALA MAL MÜDÜRLÜĞÜ'),
(63,'06','Ankara','ÇAMLIDERE','ÇAMLIDERE MAL MÜDÜRLÜĞÜ'),
(64,'06','Ankara','GÜDÜL','GÜDÜL MAL MÜDÜRLÜĞÜ'),
(65,'06','Ankara','KALECİK','KALECİK MAL MÜDÜRLÜĞÜ'),
(66,'06','Ankara','KIZILCAHAMAM','KIZILCAHAMAM MAL MÜDÜRLÜĞÜ'),
(67,'06','Ankara','NALLIHAN','NALLIHAN MAL MÜDÜRLÜĞÜ'),
(68,'06','Ankara','AKYURT','AKYURT MAL MÜDÜRLÜĞÜ'),
(69,'06','Ankara','EVREN','EVREN MAL MÜDÜRLÜĞÜ'),
(70,'06','Ankara','POLATLI','POLATLI VERGİ DAİRESİ'),
(71,'06','Ankara','ŞEREFLİKOÇHİSAR','ŞEREFLİKOÇHİSAR VERGİ DAİRESİ'),
(72,'06','Ankara','BEYPAZARI','BEYPAZARI VERGİ DAİRESİ'),
(73,'06','Ankara','ÇUBUK','ÇUBUK VERGİ DAİRESİ'),
(74,'06','Ankara','HAYMANA','HAYMANA VERGİ DAİRESİ'),
(75,'06','Ankara','ELMADAĞ','ELMADAĞ VERGİ DAİRESİ'),
(76,'06','Ankara','ÇANKAYA','VERASET VE İNTİKAL VERGİ DAİRESİ'),
(77,'06','Ankara','KAVAKLIDERE','KAVAKLIDERE VERGİ DAİRESİ'),
(78,'06','Ankara','MALTEPE','MALTEPE VERGİ DAİRESİ'),
(79,'06','Ankara','YENİMAHALLE','YENİMAHALLE VERGİ DAİRESİ'),
(80,'06','Ankara','ÇANKAYA','ÇANKAYA VERGİ DAİRESİ'),
(81,'06','Ankara','ALTINDAĞ','KIZILBEY VERGİ DAİRESİ'),
(82,'06','Ankara','ÇANKAYA','MİTHATPAŞA VERGİ DAİRESİ'),
(83,'06','Ankara','ULUS','ULUS VERGİ DAİRESİ'),
(84,'06','Ankara','ALTINDAĞ','YILDIRIMBEYAZIT VERGİ DAİRESİ'),
(85,'06','Ankara','ÇANKAYA','SEĞMENLER VERGİ DAİRESİ'),
(86,'06','Ankara','ÇANKAYA','DİKİMEVİ VERGİ DAİRESİ'),
(87,'06','Ankara','YENİMAHALLE','DOĞANBEY VERGİ DAİRESİ'),
(88,'06','Ankara','YENİMAHALLE','YEĞENBEY VERGİ DAİRESİ'),
(89,'06','Ankara','ÇANKAYA','HİTİT VERGİ DAİRESİ'),
(90,'06','Ankara','ALTINDAĞ','Y.GALİP VERGİ DAİRESİ'),
(91,'06','Ankara','ALTINDAĞ','M.KARAGÜZEL VERGİ DAİRESİ'),
(92,'06','Ankara','YENİMAHALLE','OSTİM VERGİ DAİRESİ'),
(93,'06','Ankara','GÖLBAŞI','GÖLBAŞI VERGİ DAİRESİ'),
(94,'06','Ankara','SİNCAN','SİNCAN VERGİ DAİRESİ'),
(95,'06','Ankara','ALTINDAĞ','DIŞKAPI VERGİ DAİRESİ'),
(96,'06','Ankara','ETİMESGUT','ETİMESGUT VERGİ DAİRESİ'),
(97,'06','Ankara','ÇANKAYA','BAŞKENT VERGİ DAİRESİ'),
(98,'06','Ankara','ÇANKAYA','CUMHURİYET VERGİ DAİRESİ'),
(99,'06','Ankara','KEÇİÖREN','KEÇİÖREN VERGİ DAİRESİ'),
(100,'06','Ankara','KAHRAMANKAZAN','KAHRAMANKAZAN VERGİ DAİRESİ'),
(101,'06','Ankara','YENİMAHALLE','ANADOLU İHTİSAS VERGİ DAİRESİ'),
(102,'06','Ankara','YENİMAHALLE','ANKARA İHTİSAS VERGİ DAİRESİ'),
(103,'06','Ankara','ALTINDAĞ','HARÇLAR VERGİ DAİRESİ'),
(104,'06','Ankara','YENİMAHALLE','ANKARA KURUMLAR VERGİ DAİRESİ'),
(105,'06','Ankara','YENİMAHALLE','İVEDİK VERGİ DAİRESİ'),
(106,'07','Antalya','AKSEKİ','AKSEKİ MAL MÜDÜRLÜĞÜ'),
(107,'07','Antalya','FİNİKE','FİNİKE MAL MÜDÜRLÜĞÜ'),
(108,'07','Antalya','GAZİPAŞA','GAZİPAŞA MAL MÜDÜRLÜĞÜ'),
(109,'07','Antalya','GÜNDOĞMUŞ','GÜNDOĞMUŞ MAL MÜDÜRLÜĞÜ'),
(110,'07','Antalya','KAŞ','KAŞ MAL MÜDÜRLÜĞÜ'),
(111,'07','Antalya','DEMRE','DEMRE MAL MÜDÜRLÜĞÜ'),
(112,'07','Antalya','İBRADI','İBRADI MAL MÜDÜRLÜĞÜ'),
(113,'07','Antalya','ALANYA','ALANYA VERGİ DAİRESİ'),
(114,'07','Antalya','SERİK','SERİK VERGİ DAİRESİ'),
(115,'07','Antalya','MANAVGAT','MANAVGAT VERGİ DAİRESİ'),
(116,'07','Antalya','ELMALI','ELMALI VERGİ DAİRESİ'),
(117,'07','Antalya','KEMER','KEMER VERGİ DAİRESİ'),
(118,'07','Antalya','KUMLUCA','KUMLUCA VERGİ DAİRESİ'),
(119,'07','Antalya','MURATPAŞA','ÜÇKAPILAR VERGİ DAİRESİ'),
(120,'07','Antalya','MURATPAŞA','KALEKAPI VERGİ DAİRESİ'),
(121,'07','Antalya','MURATPAŞA','MURATPAŞA VERGİ DAİRESİ'),
(122,'07','Antalya','MURATPAŞA','DÜDEN VERGİ DAİRESİ'),
(123,'07','Antalya','MURATPAŞA','ANTALYA KURUMLAR VERGİ DAİRESİ'),
(124,'07','Antalya','ANTALYA MERKEZ','ANTALYA İHTİSAS VERGİ DAİRESİ'),
(125,'07','Antalya','KORKUTELİ','KORKUTELİ VERGİ DAİRESİ'),
(126,'08','Artvin','ARDANUÇ','ARDANUÇ MAL MÜDÜRLÜĞÜ'),
(127,'08','Artvin','BORÇKA','BORÇKA MAL MÜDÜRLÜĞÜ'),
(128,'08','Artvin','ŞAVŞAT','ŞAVŞAT MAL MÜDÜRLÜĞÜ'),
(129,'08','Artvin','YUSUFELİ','YUSUFELİ MAL MÜDÜRLÜĞÜ'),
(130,'08','Artvin','MURGUL','MURGUL MAL MÜDÜRLÜĞÜ'),
(131,'08','Artvin','ARTVİN MERKEZ','ARTVİN VERGİ DAİRESİ'),
(132,'08','Artvin','HOPA','HOPA VERGİ DAİRESİ'),
(133,'08','Artvin','ARHAVİ','ARHAVİ VERGİ DAİRESİ'),
(134,'09','Aydın','BOZDOĞAN','BOZDOĞAN MAL MÜDÜRLÜĞÜ'),
(135,'09','Aydın','KARACASU','KARACASU MAL MÜDÜRLÜĞÜ'),
(136,'09','Aydın','KOÇARLI','KOÇARLI MAL MÜDÜRLÜĞÜ'),
(137,'09','Aydın','KUYUCAK','KUYUCAK MAL MÜDÜRLÜĞÜ'),
(138,'09','Aydın','SULTANHİSAR','SULTANHİSAR MAL MÜDÜRLÜĞÜ'),
(139,'09','Aydın','YENİPAZAR','YENİPAZAR MAL MÜDÜRLÜĞÜ'),
(140,'09','Aydın','BUHARKENT','BUHARKENT MAL MÜDÜRLÜĞÜ'),
(141,'09','Aydın','İNCİRLİOVA','İNCİRLİOVA MAL MÜDÜRLÜĞÜ'),
(142,'09','Aydın','KARPUZLU','KARPUZLU MAL MÜDÜRLÜĞÜ'),
(143,'09','Aydın','KÖŞK','KÖŞK MAL MÜDÜRLÜĞÜ'),
(144,'09','Aydın','EFELER','EFELER VERGİ DAİRESİ'),
(145,'09','Aydın','NAZİLLİ','NAZİLLİ VERGİ DAİRESİ'),
(146,'09','Aydın','SÖKE','SÖKE VERGİ DAİRESİ'),
(147,'09','Aydın','ÇİNE','ÇİNE VERGİ DAİRESİ'),
(148,'09','Aydın','GERMENCİK','GERMENCİK VERGİ DAİRESİ'),
(149,'09','Aydın','KUŞADASI','KUŞADASI VERGİ DAİRESİ'),
(150,'09','Aydın','EFELER','GÜZELHİSAR VERGİ DAİRESİ'),
(151,'09','Aydın','DİDİM','DİDİM VERGİ DAİRESİ'),
(152,'10','Balıkesir','BALYA','BALYA MAL MÜDÜRLÜĞÜ'),
(153,'10','Balıkesir','HAVRAN','HAVRAN MAL MÜDÜRLÜĞÜ'),
(154,'10','Balıkesir','İVRİNDİ','İVRİNDİ MAL MÜDÜRLÜĞÜ'),
(155,'10','Balıkesir','KEPSUT','KEPSUT MAL MÜDÜRLÜĞÜ'),
(156,'10','Balıkesir','MANYAS','MANYAS MAL MÜDÜRLÜĞÜ'),
(157,'10','Balıkesir','SAVAŞTEPE','SAVAŞTEPE MAL MÜDÜRLÜĞÜ'),
(158,'10','Balıkesir','MARMARA','MARMARA MAL MÜDÜRLÜĞÜ'),
(159,'10','Balıkesir','GÖMEÇ','GÖMEÇ MAL MÜDÜRLÜĞÜ'),
(160,'10','Balıkesir','KARESİ','KARESİ VERGİ DAİRESİ'),
(161,'10','Balıkesir','AYVALIK','AYVALIK VERGİ DAİRESİ'),
(162,'10','Balıkesir','BANDIRMA','BANDIRMA VERGİ DAİRESİ'),
(163,'10','Balıkesir','BURHANİYE','BURHANİYE VERGİ DAİRESİ'),
(164,'10','Balıkesir','EDREMİT','EDREMİT VERGİ DAİRESİ'),
(165,'10','Balıkesir','GÖNEN','GÖNEN VERGİ DAİRESİ'),
(166,'10','Balıkesir','SUSURLUK','SUSURLUK VERGİ DAİRESİ'),
(167,'10','Balıkesir','ERDEK','ERDEK VERGİ DAİRESİ'),
(168,'10','Balıkesir','BİGADİÇ','BİGADİÇ VERGİ DAİRESİ'),
(169,'10','Balıkesir','SINDIRGI','SINDIRGI VERGİ DAİRESİ'),
(170,'10','Balıkesir','DURSUNBEY','DURSUNBEY VERGİ DAİRESİ'),
(171,'10','Balıkesir','ALTIEYLÜL','KURTDERELİ VERGİ DAİRESİ'),
(172,'11','Bilecik','GÖLPAZARI','GÖLPAZARI MAL MÜDÜRLÜĞÜ'),
(173,'11','Bilecik','OSMANELİ','OSMANELİ MAL MÜDÜRLÜĞÜ'),
(174,'11','Bilecik','PAZARYERİ','PAZARYERİ MAL MÜDÜRLÜĞÜ'),
(175,'11','Bilecik','SÖĞÜT','SÖĞÜT MAL MÜDÜRLÜĞÜ'),
(176,'11','Bilecik','YENİPAZAR','YENİPAZAR MAL MÜDÜRLÜĞÜ'),
(177,'11','Bilecik','İNHİSAR','İNHİSAR MAL MÜDÜRLÜĞÜ'),
(178,'11','Bilecik','BİLECİK MERKEZ','BİLECİK VERGİ DAİRESİ'),
(179,'11','Bilecik','BOZÜYÜK','BOZÜYÜK VERGİ DAİRESİ'),
(180,'12','Bingöl','GENÇ','GENÇ MAL MÜDÜRLÜĞÜ'),
(181,'12','Bingöl','KARLIOVA','KARLIOVA MAL MÜDÜRLÜĞÜ'),
(182,'12','Bingöl','KIĞI','KIĞI MAL MÜDÜRLÜĞÜ'),
(183,'12','Bingöl','SOLHAN','SOLHAN MAL MÜDÜRLÜĞÜ'),
(184,'12','Bingöl','ADAKLI','ADAKLI MAL MÜDÜRLÜĞÜ'),
(185,'12','Bingöl','YAYLADERE','YAYLADERE MAL MÜDÜRLÜĞÜ'),
(186,'12','Bingöl','YEDİSU','YEDİSU MAL MÜDÜRLÜĞÜ'),
(187,'12','Bingöl','BİNGÖL MERKEZ','BİNGÖL VERGİ DAİRESİ'),
(188,'13','Bitlis','ADİLCEVAZ','ADİLCEVAZ MAL MÜDÜRLÜĞÜ'),
(189,'13','Bitlis','AHLAT','AHLAT MAL MÜDÜRLÜĞÜ'),
(190,'13','Bitlis','HİZAN','HİZAN MAL MÜDÜRLÜĞÜ'),
(191,'13','Bitlis','MUTKİ','MUTKİ MAL MÜDÜRLÜĞÜ'),
(192,'13','Bitlis','GÜROYMAK','GÜROYMAK MAL MÜDÜRLÜĞÜ'),
(193,'13','Bitlis','BİTLİS MERKEZ','BİTLİS VERGİ DAİRESİ'),
(194,'13','Bitlis','TATVAN','TATVAN VERGİ DAİRESİ'),
(195,'14','Bolu','GÖYNÜK','GÖYNÜK MAL MÜDÜRLÜĞÜ'),
(196,'14','Bolu','KIBRISCIK','KIBRISCIK MAL MÜDÜRLÜĞÜ'),
(197,'14','Bolu','MENGEN','MENGEN MAL MÜDÜRLÜĞÜ'),
(198,'14','Bolu','MUDURNU','MUDURNU MAL MÜDÜRLÜĞÜ'),
(199,'14','Bolu','SEBEN','SEBEN MAL MÜDÜRLÜĞÜ'),
(200,'14','Bolu','DÖRTDİVAN','DÖRTDİVAN MAL MÜDÜRLÜĞÜ'),
(201,'14','Bolu','YENİÇAĞA','YENİÇAĞA MAL MÜDÜRLÜĞÜ'),
(202,'14','Bolu','BOLU MERKEZ','BOLU VERGİ DAİRESİ'),
(203,'14','Bolu','GEREDE','GEREDE VERGİ DAİRESİ'),
(204,'15','Burdur','AĞLASUN','AĞLASUN MAL MÜDÜRLÜĞÜ'),
(205,'15','Burdur','GÖLHİSAR','GÖLHİSAR MAL MÜDÜRLÜĞÜ'),
(206,'15','Burdur','TEFENNİ','TEFENNİ MAL MÜDÜRLÜĞÜ'),
(207,'15','Burdur','YEŞİLOVA','YEŞİLOVA MAL MÜDÜRLÜĞÜ'),
(208,'15','Burdur','KARAMANLI','KARAMANLI MAL MÜDÜRLÜĞÜ'),
(209,'15','Burdur','KEMER','KEMER MAL MÜDÜRLÜĞÜ'),
(210,'15','Burdur','ALTINYAYLA','ALTINYAYLA MAL MÜDÜRLÜĞÜ'),
(211,'15','Burdur','ÇAVDIR','ÇAVDIR MAL MÜDÜRLÜĞÜ'),
(212,'15','Burdur','ÇELTİKÇİ','ÇELTİKÇİ MAL MÜDÜRLÜĞÜ'),
(213,'15','Burdur','BURDUR MERKEZ','BURDUR VERGİ DAİRESİ'),
(214,'15','Burdur','BUCAK','BUCAK VERGİ DAİRESİ'),
(215,'16','Bursa','KELES','KELES MAL MÜDÜRLÜĞÜ'),
(216,'16','Bursa','ORHANELİ','ORHANELİ MAL MÜDÜRLÜĞÜ'),
(217,'16','Bursa','HARMANCIK','HARMANCIK MAL MÜDÜRLÜĞÜ'),
(218,'16','Bursa','BÜYÜKORHAN','BÜYÜKORHAN MAL MÜDÜRLÜĞÜ'),
(219,'16','Bursa','GEMLİK','GEMLİK VERGİ DAİRESİ'),
(220,'16','Bursa','İNEGÖL','İNEGÖL VERGİ DAİRESİ'),
(221,'16','Bursa','KARACABEY','KARACABEY VERGİ DAİRESİ'),
(222,'16','Bursa','MUSTAFAKEMALPAŞA','MUSTAFAKEMALPAŞA VERGİ DAİRESİ'),
(223,'16','Bursa','MUDANYA','MUDANYA VERGİ DAİRESİ'),
(224,'16','Bursa','ORHANGAZİ','ORHANGAZİ VERGİ DAİRESİ'),
(225,'16','Bursa','İZNİK','İZNİK VERGİ DAİRESİ'),
(226,'16','Bursa','YENİŞEHİR','YENİŞEHİR VERGİ DAİRESİ'),
(227,'16','Bursa','BURSA MERKEZ','BURSA İHTİSAS VERGİ DAİRESİ'),
(228,'16','Bursa','OSMANGAZİ','OSMANGAZİ VERGİ DAİRESİ'),
(229,'16','Bursa','YILDIRIM','YILDIRIM VERGİ DAİRESİ'),
(230,'16','Bursa','NİLÜFER','ÇEKİRGE VERGİ DAİRESİ'),
(231,'16','Bursa','OSMANGAZİ','SETBAŞI VERGİ DAİRESİ'),
(232,'16','Bursa','NİLÜFER','ULUDAĞ VERGİ DAİRESİ'),
(233,'16','Bursa','NİLÜFER','YEŞİL VERGİ DAİRESİ'),
(234,'16','Bursa','NİLÜFER','NİLÜFER VERGİ DAİRESİ'),
(235,'16','Bursa','NİLÜFER','ERTUĞRULGAZİ VERGİ DAİRESİ'),
(236,'16','Bursa','OSMANGAZİ','GÖKDERE VERGİ DAİRESİ'),
(237,'16','Bursa','OSMANGAZİ','BURSA VER.HARÇ. VERGİ DAİRESİ'),
(238,'17','Çanakkale','AYVACIK','AYVACIK MAL MÜDÜRLÜĞÜ'),
(239,'17','Çanakkale','BAYRAMİÇ','BAYRAMİÇ MAL MÜDÜRLÜĞÜ'),
(240,'17','Çanakkale','BOZCAADA','BOZCAADA MAL MÜDÜRLÜĞÜ'),
(241,'17','Çanakkale','ECEABAT','ECEABAT MAL MÜDÜRLÜĞÜ'),
(242,'17','Çanakkale','EZİNE','EZİNE MAL MÜDÜRLÜĞÜ'),
(243,'17','Çanakkale','GÖKÇEADA','GÖKÇEADA MAL MÜDÜRLÜĞÜ'),
(244,'17','Çanakkale','LAPSEKİ','LAPSEKİ MAL MÜDÜRLÜĞÜ'),
(245,'17','Çanakkale','YENİCE','YENİCE MAL MÜDÜRLÜĞÜ'),
(246,'17','Çanakkale','ÇANAKKALE MERKEZ','ÇANAKKALE VERGİ DAİRESİ'),
(247,'17','Çanakkale','BİGA','BİGA VERGİ DAİRESİ'),
(248,'17','Çanakkale','ÇAN','ÇAN VERGİ DAİRESİ'),
(249,'17','Çanakkale','GELİBOLU','GELİBOLU VERGİ DAİRESİ'),
(250,'18','Çankırı','ÇERKEŞ','ÇERKEŞ MAL MÜDÜRLÜĞÜ'),
(251,'18','Çankırı','ELDİVAN','ELDİVAN MAL MÜDÜRLÜĞÜ'),
(252,'18','Çankırı','ILGAZ','ILGAZ MAL MÜDÜRLÜĞÜ'),
(253,'18','Çankırı','KURŞUNLU','KURŞUNLU MAL MÜDÜRLÜĞÜ'),
(254,'18','Çankırı','ORTA','ORTA MAL MÜDÜRLÜĞÜ'),
(255,'18','Çankırı','ŞABANÖZÜ','ŞABANÖZÜ MAL MÜDÜRLÜĞÜ'),
(256,'18','Çankırı','YAPRAKLI','YAPRAKLI MAL MÜDÜRLÜĞÜ'),
(257,'18','Çankırı','ATKARACALAR','ATKARACALAR MAL MÜDÜRLÜĞÜ'),
(258,'18','Çankırı','KIZILIRMAK','KIZILIRMAK MAL MÜDÜRLÜĞÜ'),
(259,'18','Çankırı','BAYRAMÖREN','BAYRAMÖREN MAL MÜDÜRLÜĞÜ'),
(260,'18','Çankırı','KORGUN','KORGUN MAL MÜDÜRLÜĞÜ'),
(261,'18','Çankırı','ÇANKIRI MERKEZ','ÇANKIRI VERGİ DAİRESİ'),
(262,'19','Çorum','ALACA','ALACA MAL MÜDÜRLÜĞÜ'),
(263,'19','Çorum','BAYAT','BAYAT MAL MÜDÜRLÜĞÜ'),
(264,'19','Çorum','İSKİLİP','İSKİLİP MAL MÜDÜRLÜĞÜ'),
(265,'19','Çorum','KARGI','KARGI MAL MÜDÜRLÜĞÜ'),
(266,'19','Çorum','MECİTÖZÜ','MECİTÖZÜ MAL MÜDÜRLÜĞÜ'),
(267,'19','Çorum','ORTAKÖY','ORTAKÖY MAL MÜDÜRLÜĞÜ'),
(268,'19','Çorum','OSMANCIK','OSMANCIK MAL MÜDÜRLÜĞÜ'),
(269,'19','Çorum','BOĞAZKALE','BOĞAZKALE MAL MÜDÜRLÜĞÜ'),
(270,'19','Çorum','UĞURLUDAĞ','UĞURLUDAĞ MAL MÜDÜRLÜĞÜ'),
(271,'19','Çorum','DODURGA','DODURGA MAL MÜDÜRLÜĞÜ'),
(272,'19','Çorum','OĞUZLAR','OĞUZLAR MAL MÜDÜRLÜĞÜ'),
(273,'19','Çorum','LAÇİN','LAÇİN MAL MÜDÜRLÜĞÜ'),
(274,'19','Çorum','ÇORUM MERKEZ','ÇORUM VERGİ DAİRESİ'),
(275,'19','Çorum','SUNGURLU','SUNGURLU VERGİ DAİRESİ'),
(276,'20','Denizli','ÇAMELİ','ÇAMELİ MAL MÜDÜRLÜĞÜ'),
(277,'20','Denizli','ÇARDAK','ÇARDAK MAL MÜDÜRLÜĞÜ'),
(278,'20','Denizli','GÜNEY','GÜNEY MAL MÜDÜRLÜĞÜ'),
(279,'20','Denizli','KALE','KALE MAL MÜDÜRLÜĞÜ'),
(280,'20','Denizli','BABADAĞ','BABADAĞ MAL MÜDÜRLÜĞÜ'),
(281,'20','Denizli','BEKİLLİ','BEKİLLİ MAL MÜDÜRLÜĞÜ'),
(282,'20','Denizli','HONAZ','HONAZ MAL MÜDÜRLÜĞÜ'),
(283,'20','Denizli','SERİNHİSAR','SERİNHİSAR MAL MÜDÜRLÜĞÜ'),
(284,'20','Denizli','PAMUKKALE','PAMUKKALE MAL MÜDÜRLÜĞÜ'),
(285,'20','Denizli','BAKLAN','BAKLAN MAL MÜDÜRLÜĞÜ'),
(286,'20','Denizli','BEYAĞAÇ','BEYAĞAÇ MAL MÜDÜRLÜĞÜ'),
(287,'20','Denizli','BOZKURT','BOZKURT MAL MÜDÜRLÜĞÜ'),
(288,'20','Denizli','MERKEZEFENDİ','SARAYLAR VERGİ DAİRESİ'),
(289,'20','Denizli','ÇINAR','ÇINAR VERGİ DAİRESİ'),
(290,'20','Denizli','MERKEZEFENDİ','GÖKPINAR VERGİ DAİRESİ'),
(291,'20','Denizli','MERKEZEFENDİ','DENİZLİ İHTİSAS VERGİ DAİRESİ'),
(292,'20','Denizli','SARAYKÖY','SARAYKÖY VERGİ DAİRESİ'),
(293,'20','Denizli','ACIPAYAM','ACIPAYAM VERGİ DAİRESİ'),
(294,'20','Denizli','TAVAS','TAVAS VERGİ DAİRESİ'),
(295,'20','Denizli','BULDAN','BULDAN VERGİ DAİRESİ'),
(296,'20','Denizli','ÇAL','ÇAL VERGİ DAİRESİ'),
(297,'20','Denizli','ÇİVRİL','ÇİVRİL VERGİ DAİRESİ'),
(298,'20','Denizli','PAMUKKALE','PAMUKKALE VERGİ DAİRESİ'),
(299,'21','Diyarbakır','ÇERMİK','ÇERMİK MAL MÜDÜRLÜĞÜ'),
(300,'21','Diyarbakır','ÇINAR','ÇINAR MAL MÜDÜRLÜĞÜ'),
(301,'21','Diyarbakır','ÇÜNGÜŞ','ÇÜNGÜŞ MAL MÜDÜRLÜĞÜ'),
(302,'21','Diyarbakır','DİCLE','DİCLE MAL MÜDÜRLÜĞÜ'),
(303,'21','Diyarbakır','HANİ','HANİ MAL MÜDÜRLÜĞÜ'),
(304,'21','Diyarbakır','HAZRO','HAZRO MAL MÜDÜRLÜĞÜ'),
(305,'21','Diyarbakır','KULP','KULP MAL MÜDÜRLÜĞÜ'),
(306,'21','Diyarbakır','LİCE','LİCE MAL MÜDÜRLÜĞÜ'),
(307,'21','Diyarbakır','SİLVAN','SİLVAN MAL MÜDÜRLÜĞÜ'),
(308,'21','Diyarbakır','EĞİL','EĞİL MAL MÜDÜRLÜĞÜ'),
(309,'21','Diyarbakır','KOCAKÖY','KOCAKÖY MAL MÜDÜRLÜĞÜ'),
(310,'21','Diyarbakır','YENİŞEHİR','GÖKALP VERGİ DAİRESİ'),
(311,'21','Diyarbakır','YENİŞEHİR','SÜLEYMANNAZİF VERGİ DAİRESİ'),
(312,'21','Diyarbakır','YENİŞEHİR','C.SITKI TARANCI VERGİ DAİRESİ'),
(313,'21','Diyarbakır','ERGANİ','ERGANİ VERGİ DAİRESİ'),
(314,'21','Diyarbakır','BİSMİL','BİSMİL VERGİ DAİRESİ'),
(315,'22','Edirne','ENEZ','ENEZ MAL MÜDÜRLÜĞÜ'),
(316,'22','Edirne','LALAPAŞA','LALAPAŞA MAL MÜDÜRLÜĞÜ'),
(317,'22','Edirne','MERİÇ','MERİÇ MAL MÜDÜRLÜĞÜ'),
(318,'22','Edirne','SÜLOĞLU','SÜLOĞLU MAL MÜDÜRLÜĞÜ'),
(319,'22','Edirne','EDİRNE MERKEZ','ARDA VERGİ DAİRESİ'),
(320,'22','Edirne','EDİRNE MERKEZ','KIRKPINAR VERGİ DAİRESİ'),
(321,'22','Edirne','KEŞAN','KEŞAN VERGİ DAİRESİ'),
(322,'22','Edirne','UZUNKÖPRÜ','UZUNKÖPRÜ VERGİ DAİRESİ'),
(323,'22','Edirne','HAVSA','HAVSA VERGİ DAİRESİ'),
(324,'22','Edirne','İPSALA','İPSALA VERGİ DAİRESİ'),
(325,'23','Elazığ','AĞIN','AĞIN MAL MÜDÜRLÜĞÜ'),
(326,'23','Elazığ','BASKİL','BASKİL MAL MÜDÜRLÜĞÜ'),
(327,'23','Elazığ','KARAKOÇAN','KARAKOÇAN MAL MÜDÜRLÜĞÜ'),
(328,'23','Elazığ','KEBAN','KEBAN MAL MÜDÜRLÜĞÜ'),
(329,'23','Elazığ','MADEN','MADEN MAL MÜDÜRLÜĞÜ'),
(330,'23','Elazığ','PALU','PALU MAL MÜDÜRLÜĞÜ'),
(331,'23','Elazığ','SİVRİCE','SİVRİCE MAL MÜDÜRLÜĞÜ'),
(332,'23','Elazığ','ARICAK','ARICAK MAL MÜDÜRLÜĞÜ'),
(333,'23','Elazığ','KOVANCILAR','KOVANCILAR MAL MÜDÜRLÜĞÜ'),
(334,'23','Elazığ','ALACAKAYA','ALACAKAYA MAL MÜDÜRLÜĞÜ'),
(335,'23','Elazığ','ELAZIĞ MERKEZ','HARPUT VERGİ DAİRESİ'),
(336,'23','Elazığ','ELAZIĞ MERKEZ','HAZAR VERGİ DAİRESİ'),
(337,'24','Erzincan','ÇAYIRLI','ÇAYIRLI MAL MÜDÜRLÜĞÜ'),
(338,'24','Erzincan','İLİÇ','İLİÇ MAL MÜDÜRLÜĞÜ'),
(339,'24','Erzincan','KEMAH','KEMAH MAL MÜDÜRLÜĞÜ'),
(340,'24','Erzincan','KEMALİYE','KEMALİYE MAL MÜDÜRLÜĞÜ'),
(341,'24','Erzincan','REFAHİYE','REFAHİYE MAL MÜDÜRLÜĞÜ'),
(342,'24','Erzincan','TERCAN','TERCAN MAL MÜDÜRLÜĞÜ'),
(343,'24','Erzincan','ÜZÜMLÜ','ÜZÜMLÜ MAL MÜDÜRLÜĞÜ'),
(344,'24','Erzincan','OTLUKBELİ','OTLUKBELİ MAL MÜDÜRLÜĞÜ'),
(345,'24','Erzincan','ERZİNCAN MERKEZ','FEVZİPAŞA VERGİ DAİRESİ'),
(346,'25','Erzurum','AŞKALE','AŞKALE MAL MÜDÜRLÜĞÜ'),
(347,'25','Erzurum','ÇAT','ÇAT MAL MÜDÜRLÜĞÜ'),
(348,'25','Erzurum','HINIS','HINIS MAL MÜDÜRLÜĞÜ'),
(349,'25','Erzurum','HORASAN','HOROSAN MAL MÜDÜRLÜĞÜ'),
(350,'25','Erzurum','İSPİR','İSPİR MAL MÜDÜRLÜĞÜ'),
(351,'25','Erzurum','KARAYAZI','KARAYAZI MAL MÜDÜRLÜĞÜ'),
(352,'25','Erzurum','NARMAN','NARMAN MAL MÜDÜRLÜĞÜ'),
(353,'25','Erzurum','OLTU','OLTU MAL MÜDÜRLÜĞÜ'),
(354,'25','Erzurum','OLUR','OLUR MAL MÜDÜRLÜĞÜ'),
(355,'25','Erzurum','PASİNLER','PASİNLER MAL MÜDÜRLÜĞÜ'),
(356,'25','Erzurum','ŞENKAYA','ŞENKAYA MAL MÜDÜRLÜĞÜ'),
(357,'25','Erzurum','TEKMAN','TEKMAN MAL MÜDÜRLÜĞÜ'),
(358,'25','Erzurum','TORTUM','TORTUM MAL MÜDÜRLÜĞÜ'),
(359,'25','Erzurum','KARAÇOBAN','KARAÇOBAN MAL MÜDÜRLÜĞÜ'),
(360,'25','Erzurum','UZUNDERE','UZUNDERE MAL MÜDÜRLÜĞÜ'),
(361,'25','Erzurum','PAZARYOLU','PAZARYOLU MAL MÜDÜRLÜĞÜ'),
(362,'25','Erzurum','AZİZİYE','AZİZİYE (ILICA) MAL MÜDÜRLÜĞÜ'),
(363,'25','Erzurum','KÖPRÜKÖY','KÖPRÜKÖY MAL MÜDÜRLÜĞÜ'),
(364,'25','Erzurum','AZİZİYE','AZİZİYE VERGİ DAİRESİ'),
(365,'25','Erzurum','YAKUTİYE','KAZIMKARABEKİR VERGİ DAİRESİ'),
(366,'26','Eskişehir','MAHMUDİYE','MAHMUDİYE MAL MÜDÜRLÜĞÜ'),
(367,'26','Eskişehir','MİHALIÇÇIK','MİHALIÇÇIK MAL MÜDÜRLÜĞÜ'),
(368,'26','Eskişehir','SARICAKAYA','SARICAKAYA MAL MÜDÜRLÜĞÜ'),
(369,'26','Eskişehir','SEYİTGAZİ','SEYİTGAZİ MAL MÜDÜRLÜĞÜ'),
(370,'26','Eskişehir','ALPU','ALPU MAL MÜDÜRLÜĞÜ'),
(371,'26','Eskişehir','BEYLİKOVA','BEYLİKOVA MAL MÜDÜRLÜĞÜ'),
(372,'26','Eskişehir','İNÖNÜ','İNÖNÜ MAL MÜDÜRLÜĞÜ'),
(373,'26','Eskişehir','GÜNYÜZÜ','GÜNYÜZÜ MAL MÜDÜRLÜĞÜ'),
(374,'26','Eskişehir','HAN','HAN MAL MÜDÜRLÜĞÜ'),
(375,'26','Eskişehir','MİHALGAZİ','MİHALGAZİ MAL MÜDÜRLÜĞÜ'),
(376,'26','Eskişehir','ODUNPAZARI','ESKİŞEHİR VERGİ DAİRESİ'),
(377,'27','Gaziantep','ARABAN','ARABAN MAL MÜDÜRLÜĞÜ'),
(378,'27','Gaziantep','OĞUZELİ','OĞUZELİ MAL MÜDÜRLÜĞÜ'),
(379,'27','Gaziantep','YAVUZELİ','YAVUZELİ MAL MÜDÜRLÜĞÜ'),
(380,'27','Gaziantep','KARKAMIŞ','KARKAMIŞ MAL MÜDÜRLÜĞÜ'),
(381,'27','Gaziantep','NURDAĞI','NURDAĞI MAL MÜDÜRLÜĞÜ'),
(382,'27','Gaziantep','NİZİP','NİZİP VERGİ DAİRESİ'),
(383,'27','Gaziantep','İSLAHİYE','İSLAHİYE VERGİ DAİRESİ'),
(384,'27','Gaziantep','ŞEHİTKAMİL','G.ANTEP İHTİSAS VERGİ DAİRESİ'),
(385,'27','Gaziantep','ŞEHİTKAMİL','SUBURCU VERGİ DAİRESİ'),
(386,'27','Gaziantep','ŞEHİTKAMİL','ŞEHİTKAMİL VERGİ DAİRESİ'),
(387,'27','Gaziantep','ŞAHİNBEY','ŞAHİNBEY VERGİ DAİRESİ'),
(388,'27','Gaziantep','ŞEHİTKAMİL','GAZİKENT VERGİ DAİRESİ'),
(389,'27','Gaziantep','ŞEHİTKAMİL','KOZANLI VERGİ DAİRESİ'),
(390,'28','Giresun','ALUCRA','ALUCRA MAL MÜDÜRLÜĞÜ'),
(391,'28','Giresun','DERELİ','DERELİ MAL MÜDÜRLÜĞÜ'),
(392,'28','Giresun','ESPİYE','ESPİYE MAL MÜDÜRLÜĞÜ'),
(393,'28','Giresun','EYNESİL','EYNESİL MAL MÜDÜRLÜĞÜ'),
(394,'28','Giresun','GÖRELE','GÖRELE MAL MÜDÜRLÜĞÜ'),
(395,'28','Giresun','KEŞAP','KEŞAP MAL MÜDÜRLÜĞÜ'),
(396,'28','Giresun','ŞEBİNKARAHİSAR','ŞEBİNKARAHİSAR MAL MÜDÜRLÜĞÜ'),
(397,'28','Giresun','TİREBOLU','TİREBOLU MAL MÜDÜRLÜĞÜ'),
(398,'28','Giresun','PİRAZİZ','PİRAZİZ MAL MÜDÜRLÜĞÜ'),
(399,'28','Giresun','YAĞLIDERE','YAĞLIDERE MAL MÜDÜRLÜĞÜ'),
(400,'28','Giresun','ÇANAKÇI','ÇANAKÇI MAL MÜDÜRLÜĞÜ'),
(401,'28','Giresun','GÜCE','GÜCE MAL MÜDÜRLÜĞÜ'),
(402,'28','Giresun','ÇAMOLUK','ÇAMOLUK MAL MÜDÜRLÜĞÜ'),
(403,'28','Giresun','DOĞANKENT','DOĞANKENT MAL MÜDÜRLÜĞÜ'),
(404,'28','Giresun','GİRESUN MERKEZ','GİRESUN VERGİ DAİRESİ'),
(405,'28','Giresun','BULANCAK','BULANCAK VERGİ DAİRESİ'),
(406,'29','Gümüşhane','KELKİT','KELKİT MAL MÜDÜRLÜĞÜ'),
(407,'29','Gümüşhane','ŞİRAN','ŞİRAN MAL MÜDÜRLÜĞÜ'),
(408,'29','Gümüşhane','TORUL','TORUL MAL MÜDÜRLÜĞÜ'),
(409,'29','Gümüşhane','KÖSE','KÖSE MAL MÜDÜRLÜĞÜ'),
(410,'29','Gümüşhane','KÜRTÜN','KÜRTÜN MAL MÜDÜRLÜĞÜ'),
(411,'29','Gümüşhane','GÜMÜŞHANE MERKEZ','GÜMÜŞHANE VERGİ DAİRESİ'),
(412,'30','Hakkari','ÇUKURCA','ÇUKURCA MAL MÜDÜRLÜĞÜ'),
(413,'30','Hakkari','ŞEMDİNLİ','ŞEMDİNLİ MAL MÜDÜRLÜĞÜ'),
(414,'30','Hakkari','DERECİK','DERECİK MAL MÜDÜRLÜĞÜ'),
(415,'30','Hakkari','HAKKARİ MERKEZ','HAKKARİ VERGİ DAİRESİ'),
(416,'30','Hakkari','YÜKSEKOVA','YÜKSEKOVA VERGİ DAİRESİ'),
(417,'31','Hatay','ALTINÖZÜ','ALTINÖZÜ MAL MÜDÜRLÜĞÜ'),
(418,'31','Hatay','HASSA','HASSA MAL MÜDÜRLÜĞÜ'),
(419,'31','Hatay','YAYLADAĞI','YAYLADAĞ MAL MÜDÜRLÜĞÜ'),
(420,'31','Hatay','ERZİN','ERZİN MAL MÜDÜRLÜĞÜ'),
(421,'31','Hatay','BELEN','BELEN MAL MÜDÜRLÜĞÜ'),
(422,'31','Hatay','KUMLU','KUMLU MAL MÜDÜRLÜĞÜ'),
(423,'31','Hatay','ANTAKYA','23TEMMUZ VERGİ DAİRESİ'),
(424,'31','Hatay','İSKENDERUN','SAHİL VERGİ DAİRESİ'),
(425,'31','Hatay','ANTAKYA','ANTAKYA VERGİ DAİRESİ'),
(426,'31','Hatay','DÖRTYOL','DÖRTYOL VERGİ DAİRESİ'),
(427,'31','Hatay','KIRIKHAN','KIRIKHAN VERGİ DAİRESİ'),
(428,'31','Hatay','REYHANLI','REYHANLI VERGİ DAİRESİ'),
(429,'31','Hatay','SAMANDAĞ','SAMANDAĞ VERGİ DAİRESİ'),
(430,'31','Hatay','ANTAKYA','ŞÜKRÜKANATLI VERGİ DAİRESİ'),
(431,'31','Hatay','AKDENİZ','AKDENİZ VERGİ DAİRESİ'),
(432,'31','Hatay','İSKENDERUN','ASIM GÜNDÜZ VERGİ DAİRESİ'),
(433,'32','Isparta','ATABEY','ATABEY MAL MÜDÜRLÜĞÜ'),
(434,'32','Isparta','GELENDOST','GELENDOST MAL MÜDÜRLÜĞÜ'),
(435,'32','Isparta','KEÇİBORLU','KEÇİBORLU MAL MÜDÜRLÜĞÜ'),
(436,'32','Isparta','SENİRKENT','SENİRKENT MAL MÜDÜRLÜĞÜ'),
(437,'32','Isparta','SÜTÇÜLER','SÜTÇÜLER MAL MÜDÜRLÜĞÜ'),
(438,'32','Isparta','ŞARKİKARAAĞAÇ','ŞARKİKARAAĞAÇ MAL MÜDÜRLÜĞÜ'),
(439,'32','Isparta','ULUBORLU','ULUBORLU MAL MÜDÜRLÜĞÜ'),
(440,'32','Isparta','AKSU','AKSU MAL MÜDÜRLÜĞÜ'),
(441,'32','Isparta','GÖNEN','GÖNEN MAL MÜDÜRLÜĞÜ'),
(442,'32','Isparta','YENİŞARBADEMLİ','YENİŞARBADEMLİ M MAL MÜDÜRLÜĞÜ'),
(443,'32','Isparta','ISPARTA MERKEZ','DAVRAZ VERGİ DAİRESİ'),
(444,'32','Isparta','ISPARTA MERKEZ','KAYMAKKAPI VERGİ DAİRESİ'),
(445,'32','Isparta','EĞİRDİR','EĞİRDİR VERGİ DAİRESİ'),
(446,'32','Isparta','YALVAÇ','YALVAÇ VERGİ DAİRESİ'),
(447,'33','Mersin','GÜLNAR','GÜLNAR MAL MÜDÜRLÜĞÜ'),
(448,'33','Mersin','AYDINCIK','AYDINCIK MAL MÜDÜRLÜĞÜ'),
(449,'33','Mersin','BOZYAZI','BOZYAZI MAL MÜDÜRLÜĞÜ'),
(450,'33','Mersin','ÇAMLIYAYLA','ÇAMLIYAYLA MAL MÜDÜRLÜĞÜ'),
(451,'33','Mersin','ERDEMLİ','ERDEMLİ VERGİ DAİRESİ'),
(452,'33','Mersin','SİLİFKE','SİLİFKE VERGİ DAİRESİ'),
(453,'33','Mersin','ANAMUR','ANAMUR VERGİ DAİRESİ'),
(454,'33','Mersin','TARSUS','KIZILMURAT VERGİ DAİRESİ'),
(455,'33','Mersin','TARSUS','ŞEHİTKERİM VERGİ DAİRESİ'),
(456,'33','Mersin','AKDENİZ','İSTİKLAL VERGİ DAİRESİ'),
(457,'33','Mersin','AKDENİZ','URAY VERGİ DAİRESİ'),
(458,'33','Mersin','AKDENİZ','LİMAN VERGİ DAİRESİ'),
(459,'33','Mersin','AKDENİZ','TOROS VERGİ DAİRESİ'),
(460,'33','Mersin','AKDENİZ','MERSİN İHTİSAS VERGİ DAİRESİ'),
(461,'33','Mersin','MUT','MUT VERGİ DAİRESİ'),
(462,'34','İstanbul','SİLİVRİ','SİLİVRİ VERGİ DAİRESİ'),
(463,'34','İstanbul','BÜYÜKÇEKMECE','BÜYÜKÇEKMECE VERGİ DAİRESİ'),
(464,'34','İstanbul','ŞİLE','ŞİLE VERGİ DAİRESİ'),
(465,'34','İstanbul','FATİH','HALİÇ İHTİSAS VERGİ DAİRESİ'),
(466,'34','İstanbul','FATİH','VATAN İHTİSAS VERGİ DAİRESİ'),
(467,'34','İstanbul','ÜMRANİYE','ÇAMLICA İHTİSAS VERGİ DAİRESİ'),
(468,'34','İstanbul','ÜMRANİYE','ALEMDAĞ VERGİ DAİRESİ'),
(469,'34','İstanbul','FATİH','YENİKAPI VERGİ DAİRESİ'),
(470,'34','İstanbul','ATAŞEHİR','BÜYÜK MÜK. VD. B VERGİ DAİRESİ'),
(471,'34','İstanbul','FATİH','BOĞAZİÇİ KUR. VERGİ DAİRESİ'),
(472,'34','İstanbul','MARMARA','MARMARA KUR. VERGİ DAİRESİ'),
(473,'34','İstanbul','FATİH','DAVUTPAŞA VERGİ DAİRESİ'),
(474,'34','İstanbul','ESENLER','ESENLER VERGİ DAİRESİ'),
(475,'34','İstanbul','FATİH','FATİH VERGİ DAİRESİ'),
(476,'34','İstanbul','ESENLER','KÜÇÜKKÖY VERGİ DAİRESİ'),
(477,'34','İstanbul','BAHÇELİEVLER','MERTER VERGİ DAİRESİ'),
(478,'34','İstanbul','SULTANBEYLİ','SULTANBEYLİ VERGİ DAİRESİ'),
(479,'34','İstanbul','ATAŞEHİR','ANADOLU KURUMLAR VERGİ DAİRESİ'),
(480,'34','İstanbul','TUZLA','TUZLA VERGİ DAİRESİ'),
(481,'34','İstanbul','ATAŞEHİR','KOZYATAĞI VERGİ DAİRESİ'),
(482,'34','İstanbul','ŞİŞLİ','MASLAK VERGİ DAİRESİ'),
(483,'34','İstanbul','ŞİŞLİ','ZİNCİRLİKUYU VERGİ DAİRESİ'),
(484,'34','İstanbul','BAŞAKŞEHİR','İKİTELLİ VERGİ DAİRESİ'),
(485,'34','İstanbul','BEŞİKTAŞ','BEŞİKTAŞ VERGİ DAİRESİ'),
(486,'34','İstanbul','ÜMRANİYE','ÜMRANİYE VERGİ DAİRESİ'),
(487,'34','İstanbul','FATİH','YEDİTEPE VERGİ DAİRESİ'),
(488,'34','İstanbul','ŞİŞLİ','KASIMPAŞA VERGİ DAİRESİ'),
(489,'34','İstanbul','ATAŞEHİR','ERENKÖY VERGİ DAİRESİ'),
(490,'34','İstanbul','FATİH','HİSAR VERGİ DAİRESİ'),
(491,'34','İstanbul','ESENLER','TUNA VERGİ DAİRESİ'),
(492,'34','İstanbul','ATAŞEHİR','RIHTIM VERGİ DAİRESİ'),
(493,'34','İstanbul','GÜNGÖREN','GÜNGÖREN VERGİ DAİRESİ'),
(494,'34','İstanbul','KOCASİNAN','KOCASİNAN VERGİ DAİRESİ'),
(495,'34','İstanbul','BAHÇELİEVLER','GÜNEŞLİ VERGİ DAİRESİ'),
(496,'34','İstanbul','KARTAL','KÜÇÜKYALI VERGİ DAİRESİ'),
(497,'34','İstanbul','PENDİK','PENDİK VERGİ DAİRESİ'),
(498,'34','İstanbul','BAYRAMPAŞA','BAYRAMPAŞA VERGİ DAİRESİ'),
(499,'34','İstanbul','FATİH','BEYAZIT VERGİ DAİRESİ'),
(500,'34','İstanbul','BEYOĞLU','BEYOĞLU VERGİ DAİRESİ'),
(501,'34','İstanbul','GAZİOSMANPAŞA','GAZİOSMANPAŞA VERGİ DAİRESİ'),
(502,'34','İstanbul','KADIKÖY','GÖZTEPE VERGİ DAİRESİ'),
(503,'34','İstanbul','FATİH','HOCAPAŞA VERGİ DAİRESİ'),
(504,'34','İstanbul','KADIKÖY','KADIKÖY VERGİ DAİRESİ'),
(505,'34','İstanbul','FATİH','KOCAMUSTAFAPAŞA VERGİ DAİRESİ'),
(506,'34','İstanbul','ŞİŞLİ','MECİDİYEKÖY VERGİ DAİRESİ'),
(507,'34','İstanbul','ŞİŞLİ','ŞİŞLİ VERGİ DAİRESİ'),
(508,'34','İstanbul','ÜSKÜDAR','ÜSKÜDAR VERGİ DAİRESİ'),
(509,'34','İstanbul','BAŞAKŞEHİR','HALKALI VERGİ DAİRESİ'),
(510,'34','İstanbul','KAĞITHANE','KAĞITHANE VERGİ DAİRESİ'),
(511,'34','İstanbul','ZEYTİNBURNU','ZEYTİNBURNU VERGİ DAİRESİ'),
(512,'34','İstanbul','BEYKOZ','BEYKOZ VERGİ DAİRESİ'),
(513,'34','İstanbul','SARIYER','SARIYER VERGİ DAİRESİ'),
(514,'34','İstanbul','BAKIRKÖY','BAKIRKÖY VERGİ DAİRESİ'),
(515,'34','İstanbul','KARTAL','KARTAL VERGİ DAİRESİ'),
(516,'34','İstanbul','ÜMRANİYE','NAKİL VASITA. VERGİ DAİRESİ'),
(517,'34','İstanbul','ÜMRANİYE','SARIGAZİ VERGİ DAİRESİ'),
(518,'34','İstanbul','ESENLER','ATIŞALANI VERGİ DAİRESİ'),
(519,'34','İstanbul','KARTAL','YAKACIK VERGİ DAİRESİ'),
(520,'34','İstanbul','BAHÇELİEVLER','YENİ BOSNA VERGİ DAİRESİ'),
(521,'34','İstanbul','AVCILAR','AVCILAR VERGİ DAİRESİ'),
(522,'34','İstanbul','ADALAR','ADALAR VERGİ DAİRESİ'),
(523,'34','İstanbul','KÜÇÜKÇEKMECE','KÜÇÜKÇEKMECE VERGİ DAİRESİ'),
(524,'34','İstanbul','BEYLİKDÜZÜ','BEYLİKDÜZÜ VERGİ DAİRESİ'),
(525,'34','İstanbul','ESENYURT','ESENYURT VERGİ DAİRESİ'),
(526,'35','İzmir','DİKİLİ','DİKİLİ MAL MÜDÜRLÜĞÜ'),
(527,'35','İzmir','FOÇA','FOÇA MAL MÜDÜRLÜĞÜ'),
(528,'35','İzmir','KARABURUN','KARABURUN MAL MÜDÜRLÜĞÜ'),
(529,'35','İzmir','SEFERİHİSAR','SEFERİHİSAR MAL MÜDÜRLÜĞÜ'),
(530,'35','İzmir','BEYDAĞ','BEYDAĞ MAL MÜDÜRLÜĞÜ'),
(531,'35','İzmir','BAYINDIR','BAYINDIR VERGİ DAİRESİ'),
(532,'35','İzmir','BERGAMA','BERGAMA VERGİ DAİRESİ'),
(533,'35','İzmir','MENEMEN','MENEMEN VERGİ DAİRESİ'),
(534,'35','İzmir','ÖDEMİŞ','ÖDEMİŞ VERGİ DAİRESİ'),
(535,'35','İzmir','TİRE','TİRE VERGİ DAİRESİ'),
(536,'35','İzmir','TORBALI','TORBALI VERGİ DAİRESİ'),
(537,'35','İzmir','KEMALPAŞA','KEMALPAŞA VERGİ DAİRESİ'),
(538,'35','İzmir','URLA','URLA VERGİ DAİRESİ'),
(539,'35','İzmir','SELÇUK','SELÇUK VERGİ DAİRESİ'),
(540,'35','İzmir','KINIK','KINIK VERGİ DAİRESİ'),
(541,'35','İzmir','KİRAZ','KİRAZ VERGİ DAİRESİ'),
(542,'35','İzmir','ÇEŞME','ÇEŞME VERGİ DAİRESİ'),
(543,'35','İzmir','ALİAĞA','ALİAĞA VERGİ DAİRESİ'),
(544,'35','İzmir','MENDERES','MENDERES VERGİ DAİRESİ'),
(545,'35','İzmir','KARABAĞLAR','İZMİR İHTİSAS VERGİ DAİRESİ'),
(546,'35','İzmir','KARABAĞLAR','9 EYLÜL VERGİ DAİRESİ'),
(547,'35','İzmir','KARŞIYAKA','YAMANLAR VERGİ DAİRESİ'),
(548,'35','İzmir','BORNOVA','BELKAHVE VERGİ DAİRESİ'),
(549,'35','İzmir','KARŞIYAKA','KARŞIYAKA VERGİ DAİRESİ'),
(550,'35','İzmir','KONAK','KEMERALTI VERGİ DAİRESİ'),
(551,'35','İzmir','KONAK','KONAK VERGİ DAİRESİ'),
(552,'35','İzmir','KONAK','KORDON VERGİ DAİRESİ'),
(553,'35','İzmir','BUCA','ŞİRİNYER VERGİ DAİRESİ'),
(554,'35','İzmir','BUCA','KADİFEKALE VERGİ DAİRESİ'),
(555,'35','İzmir','BUCA','TAŞITLAR VERGİ DAİRESİ'),
(556,'35','İzmir','BORNOVA','HASAN TAHSİN VERGİ DAİRESİ'),
(557,'35','İzmir','BORNOVA','BORNOVA VERGİ DAİRESİ'),
(558,'35','İzmir','BALÇOVA','BALÇOVA VERGİ DAİRESİ'),
(559,'35','İzmir','GAZİEMİR','GAZİEMİR VERGİ DAİRESİ'),
(560,'35','İzmir','KONAK','EGE VERGİ DAİRESİ'),
(561,'35','İzmir','ÇİĞLİ','ÇİĞLİ VERGİ DAİRESİ'),
(562,'35','İzmir','BAYRAKLI','ÇAKABEY İHTİSAS VERGİ DAİRESİ'),
(563,'36','Kars','ARPAÇAY','ARPAÇAY MAL MÜDÜRLÜĞÜ'),
(564,'36','Kars','DİGOR','DİGOR MAL MÜDÜRLÜĞÜ'),
(565,'36','Kars','KAĞIZMAN','KAĞIZMAN MAL MÜDÜRLÜĞÜ'),
(566,'36','Kars','SARIKAMIŞ','SARIKAMIŞ MAL MÜDÜRLÜĞÜ'),
(567,'36','Kars','SELİM','SELİM MAL MÜDÜRLÜĞÜ'),
(568,'36','Kars','SUSUZ','SUSUZ MAL MÜDÜRLÜĞÜ'),
(569,'36','Kars','AKYAKA','AKYAKA MAL MÜDÜRLÜĞÜ'),
(570,'36','Kars','KARS MERKEZ','KARS VERGİ DAİRESİ'),
(571,'37','Kastamonu','ARAÇ','ARAÇ MAL MÜDÜRLÜĞÜ'),
(572,'37','Kastamonu','AZDAVAY','AZDAVAY MAL MÜDÜRLÜĞÜ'),
(573,'37','Kastamonu','BOZKURT','BOZKURT MAL MÜDÜRLÜĞÜ'),
(574,'37','Kastamonu','CİDE','CİDE MAL MÜDÜRLÜĞÜ'),
(575,'37','Kastamonu','ÇATALZEYTİN','ÇATALZEYTİN MAL MÜDÜRLÜĞÜ'),
(576,'37','Kastamonu','DADAY','DADAY MAL MÜDÜRLÜĞÜ'),
(577,'37','Kastamonu','DEVREKANİ','DEVREKANİ MAL MÜDÜRLÜĞÜ'),
(578,'37','Kastamonu','İNEBOLU','İNEBOLU MAL MÜDÜRLÜĞÜ'),
(579,'37','Kastamonu','KÜRE','KÜRE MAL MÜDÜRLÜĞÜ'),
(580,'37','Kastamonu','ABANA','ABANA MAL MÜDÜRLÜĞÜ'),
(581,'37','Kastamonu','İHSANGAZİ','İHSANGAZİ MAL MÜDÜRLÜĞÜ'),
(582,'37','Kastamonu','PINARBAŞI','PINARBAŞI MAL MÜDÜRLÜĞÜ'),
(583,'37','Kastamonu','ŞENPAZAR','ŞENPAZAR MAL MÜDÜRLÜĞÜ'),
(584,'37','Kastamonu','AĞLI','AĞLI MAL MÜDÜRLÜĞÜ'),
(585,'37','Kastamonu','DOĞANYURT','DOĞANYURT MAL MÜDÜRLÜĞÜ'),
(586,'37','Kastamonu','HANÖNÜ','HANÖNÜ MAL MÜDÜRLÜĞÜ'),
(587,'37','Kastamonu','SEYDİLER','SEYDİLER MAL MÜDÜRLÜĞÜ'),
(588,'37','Kastamonu','KASTAMONU MERKEZ','KASTAMONU VERGİ DAİRESİ'),
(589,'37','Kastamonu','TOSYA','TOSYA VERGİ DAİRESİ'),
(590,'37','Kastamonu','TAŞKÖPRÜ','TAŞKÖPRÜ VERGİ DAİRESİ'),
(591,'38','Kayseri','FELAHİYE','FELAHİYE MAL MÜDÜRLÜĞÜ'),
(592,'38','Kayseri','İNCESU','İNCESU MAL MÜDÜRLÜĞÜ'),
(593,'38','Kayseri','SARIOĞLAN','SARIOĞLAN MAL MÜDÜRLÜĞÜ'),
(594,'38','Kayseri','SARIZ','SARIZ MAL MÜDÜRLÜĞÜ'),
(595,'38','Kayseri','TOMARZA','TOMARZA MAL MÜDÜRLÜĞÜ'),
(596,'38','Kayseri','YAHYALI','YAHYALI MAL MÜDÜRLÜĞÜ'),
(597,'38','Kayseri','YEŞİLHİSAR','YEŞİLHİSAR MAL MÜDÜRLÜĞÜ'),
(598,'38','Kayseri','AKKIŞLA','AKKIŞLA MAL MÜDÜRLÜĞÜ'),
(599,'38','Kayseri','HACILAR','HACILAR MAL MÜDÜRLÜĞÜ'),
(600,'38','Kayseri','ÖZVATAN','ÖZVATAN MAL MÜDÜRLÜĞÜ'),
(601,'38','Kayseri','DEVELİ','DEVELİ VERGİ DAİRESİ'),
(602,'38','Kayseri','PINARBAŞI','PINARBAŞI VERGİ DAİRESİ'),
(603,'38','Kayseri','BÜNYAN','BÜNYAN VERGİ DAİRESİ'),
(604,'38','Kayseri','KOCASİNAN','KAYSERİ İHTİSAS VERGİ DAİRESİ'),
(605,'38','Kayseri','KOCASİNAN','MİMARSİNAN VERGİ DAİRESİ'),
(606,'38','Kayseri','KOCASİNAN','ERCİYES VERGİ DAİRESİ'),
(607,'38','Kayseri','KOCASİNAN','KALEÖNÜ VERGİ DAİRESİ'),
(608,'38','Kayseri','KOCASİNAN','GEVHER NESİBE VERGİ DAİRESİ'),
(609,'39','Kırklareli','DEMİRKÖY','DEMİRKÖY MAL MÜDÜRLÜĞÜ'),
(610,'39','Kırklareli','KOFCAZ','KOFCAZ MAL MÜDÜRLÜĞÜ'),
(611,'39','Kırklareli','PEHLİVANKÖY','PEHLİVANKÖY MAL MÜDÜRLÜĞÜ'),
(612,'39','Kırklareli','PINARHİSAR','PINARHİSAR MAL MÜDÜRLÜĞÜ'),
(613,'39','Kırklareli','VİZE','VİZE MAL MÜDÜRLÜĞÜ'),
(614,'39','Kırklareli','KIRKLARELİ MERKEZ','KIRKLARELİ VERGİ DAİRESİ'),
(615,'39','Kırklareli','LÜLEBURGAZ','LÜLEBURGAZ VERGİ DAİRESİ'),
(616,'39','Kırklareli','BABAESKİ','BABAESKİ VERGİ DAİRESİ'),
(617,'40','Kırşehir','ÇİÇEKDAĞI','ÇİÇEKDAĞI MAL MÜDÜRLÜĞÜ'),
(618,'40','Kırşehir','MUCUR','MUCUR MAL MÜDÜRLÜĞÜ'),
(619,'40','Kırşehir','AKPINAR','AKPINAR MAL MÜDÜRLÜĞÜ'),
(620,'40','Kırşehir','AKÇAKENT','AKÇAKENT MAL MÜDÜRLÜĞÜ'),
(621,'40','Kırşehir','BOZTEPE','BOZTEPE MAL MÜDÜRLÜĞÜ'),
(622,'40','Kırşehir','KIRŞEHİR MERKEZ','KIRŞEHİR VERGİ DAİRESİ'),
(623,'40','Kırşehir','KAMAN','KAMAN VERGİ DAİRESİ'),
(624,'41','Kocaeli','KANDIRA','KANDIRA MAL MÜDÜRLÜĞÜ'),
(625,'41','Kocaeli','GEBZE','ULUÇINAR VERGİ DAİRESİ'),
(626,'41','Kocaeli','GEBZE','İLYASBEY VERGİ DAİRESİ'),
(627,'41','Kocaeli','GÖLCÜK','GÖLCÜK VERGİ DAİRESİ'),
(628,'41','Kocaeli','KARAMÜRSEL','KARAMÜRSEL VERGİ DAİRESİ'),
(629,'41','Kocaeli','KÖRFEZ','KÖRFEZ VERGİ DAİRESİ'),
(630,'41','Kocaeli','DERİNCE','DERİNCE VERGİ DAİRESİ'),
(631,'41','Kocaeli','DERİNCE','KOCAELİ İHTİSAS VERGİ DAİRESİ'),
(632,'41','Kocaeli','DERİNCE','TEPECİK VERGİ DAİRESİ'),
(633,'41','Kocaeli','İZMİT','ALEMDAR VERGİ DAİRESİ'),
(634,'41','Kocaeli','GEBZE','GEBZE İHTİSAS VERGİ DAİRESİ'),
(635,'41','Kocaeli','İZMİT','ACISU VERGİ DAİRESİ'),
(636,'42','Konya','BOZKIR','BOZKIR MAL MÜDÜRLÜĞÜ'),
(637,'42','Konya','DOĞANHİSAR','DOĞANHİSAR MAL MÜDÜRLÜĞÜ'),
(638,'42','Konya','HADİM','HADİM MAL MÜDÜRLÜĞÜ'),
(639,'42','Konya','KADINHANI','KADINHAN MAL MÜDÜRLÜĞÜ'),
(640,'42','Konya','SARAYÖNÜ','SARAYÖNÜ MAL MÜDÜRLÜĞÜ'),
(641,'42','Konya','YUNAK','YUNAK MAL MÜDÜRLÜĞÜ'),
(642,'42','Konya','AKÖREN','AKÖREN MAL MÜDÜRLÜĞÜ'),
(643,'42','Konya','ALTINEKİN','ALTINEKİN MAL MÜDÜRLÜĞÜ'),
(644,'42','Konya','DEREBUCAK','DEREBUCAK MAL MÜDÜRLÜĞÜ'),
(645,'42','Konya','HÜYÜK','HÜYÜK MAL MÜDÜRLÜĞÜ'),
(646,'42','Konya','TAŞKENT','TAŞKENT MAL MÜDÜRLÜĞÜ'),
(647,'42','Konya','AHIRLI','AHIRLI MAL MÜDÜRLÜĞÜ'),
(648,'42','Konya','ÇELTİK','ÇELTİK MAL MÜDÜRLÜĞÜ'),
(649,'42','Konya','DERBENT','DERBENT MAL MÜDÜRLÜĞÜ'),
(650,'42','Konya','EMİRGAZİ','EMİRGAZİ MAL MÜDÜRLÜĞÜ'),
(651,'42','Konya','GÜNEYSINIR','GÜNEYSINIR MAL MÜDÜRLÜĞÜ'),
(652,'42','Konya','HALKAPINAR','HALKAPINAR MAL MÜDÜRLÜĞÜ'),
(653,'42','Konya','TUZLUKCU','TUZLUKCU MAL MÜDÜRLÜĞÜ'),
(654,'42','Konya','YALIHÜYÜK','YALIHÜYÜK MAL MÜDÜRLÜĞÜ'),
(655,'42','Konya','AKŞEHİR','AKŞEHİR VERGİ DAİRESİ'),
(656,'42','Konya','EREĞLİ','EREĞLİ VERGİ DAİRESİ'),
(657,'42','Konya','BEYŞEHİR','BEYŞEHİR VERGİ DAİRESİ'),
(658,'42','Konya','CİHANBEYLİ','CİHANBEYLİ VERGİ DAİRESİ'),
(659,'42','Konya','ÇUMRA','ÇUMRA VERGİ DAİRESİ'),
(660,'42','Konya','SEYDİŞEHİR','SEYDİŞEHİR VERGİ DAİRESİ'),
(661,'42','Konya','ILGIN','ILGIN VERGİ DAİRESİ'),
(662,'42','Konya','KULU','KULU VERGİ DAİRESİ'),
(663,'42','Konya','KARAPINAR','KARAPINAR VERGİ DAİRESİ'),
(664,'42','Konya','SELÇUKLU','KONYA İHTİSAS VERGİ DAİRESİ'),
(665,'42','Konya','SELÇUK','SELÇUK VERGİ DAİRESİ'),
(666,'42','Konya','SELÇUKLU','MEVLANA VERGİ DAİRESİ'),
(667,'42','Konya','MERAM','MERAM VERGİ DAİRESİ'),
(668,'42','Konya','SELÇUKLU','ALAADDİN VERGİ DAİRESİ'),
(669,'43','Kütahya','ALTINTAŞ','ALTINTAŞ MAL MÜDÜRLÜĞÜ'),
(670,'43','Kütahya','DOMANİÇ','DOMANİÇ MAL MÜDÜRLÜĞÜ'),
(671,'43','Kütahya','ASLANAPA','ASLANAPA MAL MÜDÜRLÜĞÜ'),
(672,'43','Kütahya','DUMLUPINAR','DUMLUPINAR MAL MÜDÜRLÜĞÜ'),
(673,'43','Kütahya','HİSARCIK','HİSARCIK MAL MÜDÜRLÜĞÜ'),
(674,'43','Kütahya','ŞAPHANE','ŞAPHANE MAL MÜDÜRLÜĞÜ'),
(675,'43','Kütahya','ÇAVDARHİSAR','ÇAVDARHİSAR MAL MÜDÜRLÜĞÜ'),
(676,'43','Kütahya','PAZARLAR','PAZARLAR MAL MÜDÜRLÜĞÜ'),
(677,'43','Kütahya','KÜTAHYA MERKEZ','30 AĞUSTOS VERGİ DAİRESİ'),
(678,'43','Kütahya','GEDİZ','GEDİZ VERGİ DAİRESİ'),
(679,'43','Kütahya','SİMAV','SİMAV VERGİ DAİRESİ'),
(680,'43','Kütahya','TAVŞANLI','TAVŞANLI VERGİ DAİRESİ'),
(681,'43','Kütahya','EMET','EMET VERGİ DAİRESİ'),
(682,'43','Kütahya','KÜTAHYA MERKEZ','ÇİNİLİ VERGİ DAİRESİ'),
(683,'44','Malatya','AKÇADAĞ','AKÇADAĞ MAL MÜDÜRLÜĞÜ'),
(684,'44','Malatya','ARAPGİR','ARAPGİR MAL MÜDÜRLÜĞÜ'),
(685,'44','Malatya','ARGUVAN','ARGUVAN MAL MÜDÜRLÜĞÜ'),
(686,'44','Malatya','DARENDE','DARENDE MAL MÜDÜRLÜĞÜ'),
(687,'44','Malatya','DOĞANŞEHİR','DOĞANŞEHİR MAL MÜDÜRLÜĞÜ'),
(688,'44','Malatya','HEKİMHAN','HEKİMHAN MAL MÜDÜRLÜĞÜ'),
(689,'44','Malatya','PÜTÜRGE','PÜTÜRGE MAL MÜDÜRLÜĞÜ'),
(690,'44','Malatya','YEŞİLYURT','YEŞİLYURT MAL MÜDÜRLÜĞÜ'),
(691,'44','Malatya','BATTALGAZİ','BATTALGAZİ MAL MÜDÜRLÜĞÜ'),
(692,'44','Malatya','DOĞANYOL','DOĞANYOL MAL MÜDÜRLÜĞÜ'),
(693,'44','Malatya','KALE','KALE MAL MÜDÜRLÜĞÜ'),
(694,'44','Malatya','KULUNCAK','KULUNCAK MAL MÜDÜRLÜĞÜ'),
(695,'44','Malatya','YAZIHAN','YAZIHAN MAL MÜDÜRLÜĞÜ'),
(696,'44','Malatya','MALATYA MERKEZ','FIRAT VERGİ DAİRESİ'),
(697,'44','Malatya','BEYDAĞ','BEYDAĞI VERGİ DAİRESİ'),
(698,'45','Manisa','SELENDİ','SELENDİ MAL MÜDÜRLÜĞÜ'),
(699,'45','Manisa','AHMETLİ','AHMETLİ MAL MÜDÜRLÜĞÜ'),
(700,'45','Manisa','GÖLMARMARA','GÖLMARMARA MAL MÜDÜRLÜĞÜ'),
(701,'45','Manisa','KÖPRÜBAŞI','KÖPRÜBAŞI MAL MÜDÜRLÜĞÜ'),
(702,'45','Manisa','AKHİSAR','AKHİSAR VERGİ DAİRESİ'),
(703,'45','Manisa','ALAŞEHİR','ALAŞEHİR VERGİ DAİRESİ'),
(704,'45','Manisa','DEMİRCİ','DEMİRCİ VERGİ DAİRESİ'),
(705,'45','Manisa','KIRKAĞAÇ','KIRKAĞAÇ VERGİ DAİRESİ'),
(706,'45','Manisa','SALİHLİ','SALİHLİ ADİL ORAL VERGİ DAİRESİ'),
(707,'45','Manisa','SARIGÖL','SARIGÖL VERGİ DAİRESİ'),
(708,'45','Manisa','SARUHANLI','SARUHANLI VERGİ DAİRESİ'),
(709,'45','Manisa','SOMA','SOMA VERGİ DAİRESİ'),
(710,'45','Manisa','TURGUTLU','TURGUTLU VERGİ DAİRESİ'),
(711,'45','Manisa','GÖRDES','GÖRDES VERGİ DAİRESİ'),
(712,'45','Manisa','KULA','KULA VERGİ DAİRESİ'),
(713,'45','Manisa','MANİSA MERKEZ','MANİSA İHTİSAS VERGİ DAİRESİ'),
(714,'45','Manisa','MANİSA MERKEZ','ŞEHİT CİHAN GÜNEŞ VERGİ DAİRESİ'),
(715,'45','Manisa','MANİSA MERKEZ','MESİR VERGİ DAİRESİ'),
(716,'46','Kahramanmaraş','ANDIRIN','ANDIRIN MAL MÜDÜRLÜĞÜ'),
(717,'46','Kahramanmaraş','GÖKSUN','GÖKSUN MAL MÜDÜRLÜĞÜ'),
(718,'46','Kahramanmaraş','TÜRKOĞLU','TÜRKOĞLU MAL MÜDÜRLÜĞÜ'),
(719,'46','Kahramanmaraş','ÇAĞLAYANCERİT','ÇAĞLIYANCERİT MAL MÜDÜRLÜĞÜ'),
(720,'46','Kahramanmaraş','EKİNÖZÜ','EKİNÖZÜ MAL MÜDÜRLÜĞÜ'),
(721,'46','Kahramanmaraş','NURHAK','NURHAK MAL MÜDÜRLÜĞÜ'),
(722,'46','Kahramanmaraş','KAHRAMANMARAŞ MERKEZ','ASLANBEY VERGİ DAİRESİ'),
(723,'46','Kahramanmaraş','ELBİSTAN','ELBİSTAN VERGİ DAİRESİ'),
(724,'46','Kahramanmaraş','AFŞİN','AFŞİN VERGİ DAİRESİ'),
(725,'46','Kahramanmaraş','PAZARCIK','PAZARCIK VERGİ DAİRESİ'),
(726,'46','Kahramanmaraş','AKSU','AKSU VERGİ DAİRESİ'),
(727,'47','Mardin','DERİK','DERİK MAL MÜDÜRLÜĞÜ'),
(728,'47','Mardin','MAZIDAĞI','MAZIDAĞI MAL MÜDÜRLÜĞÜ'),
(729,'47','Mardin','MİDYAT','MİDYAT MAL MÜDÜRLÜĞÜ'),
(730,'47','Mardin','ÖMERLİ','ÖMERLİ MAL MÜDÜRLÜĞÜ'),
(731,'47','Mardin','SAVUR','SAVUR MAL MÜDÜRLÜĞÜ'),
(732,'47','Mardin','DARGEÇİT','DARGEÇİT MAL MÜDÜRLÜĞÜ'),
(733,'47','Mardin','YEŞİLLİ','YEŞİLLİ MAL MÜDÜRLÜĞÜ'),
(734,'47','Mardin','ARTUKLU','MARDİN VERGİ DAİRESİ'),
(735,'47','Mardin','KIZILTEPE','KIZILTEPE VERGİ DAİRESİ'),
(736,'47','Mardin','NUSAYBİN','NUSAYBİN VERGİ DAİRESİ'),
(737,'48','Muğla','DATÇA','DATÇA MAL MÜDÜRLÜĞÜ'),
(738,'48','Muğla','ULA','ULA MAL MÜDÜRLÜĞÜ'),
(739,'48','Muğla','DALAMAN','DALAMAN MAL MÜDÜRLÜĞÜ'),
(740,'48','Muğla','ORTACA','ORTACA MAL MÜDÜRLÜĞÜ'),
(741,'48','Muğla','KAVAKLIDERE','KAVAKLIDERE MAL MÜDÜRLÜĞÜ'),
(742,'48','Muğla','SEYDİKEMER','SEYDİKEMER MAL MÜDÜRLÜĞÜ'),
(743,'48','Muğla','MENTEŞE','MUĞLA VERGİ DAİRESİ'),
(744,'48','Muğla','BODRUM','BODRUM VERGİ DAİRESİ'),
(745,'48','Muğla','FETHİYE','FETHİYE VERGİ DAİRESİ'),
(746,'48','Muğla','KÖYCEĞİZ','KÖYCEĞİZ VERGİ DAİRESİ'),
(747,'48','Muğla','MİLAS','MİLAS VERGİ DAİRESİ'),
(748,'48','Muğla','MARMARİS','MARMARİS VERGİ DAİRESİ'),
(749,'48','Muğla','YATAĞAN','YATAĞAN VERGİ DAİRESİ'),
(750,'49','Muş','BULANIK','BULANIK MAL MÜDÜRLÜĞÜ'),
(751,'49','Muş','MALAZGİRT','MALAZGİRT MAL MÜDÜRLÜĞÜ'),
(752,'49','Muş','VARTO','VARTO MAL MÜDÜRLÜĞÜ'),
(753,'49','Muş','HASKÖY','HASKÖY MAL MÜDÜRLÜĞÜ'),
(754,'49','Muş','KORKUT','KORKUT MAL MÜDÜRLÜĞÜ'),
(755,'49','Muş','MUŞ MERKEZ','MUŞ VERGİ DAİRESİ'),
(756,'50','Nevşehir','AVANOS','AVANOS MAL MÜDÜRLÜĞÜ'),
(757,'50','Nevşehir','DERİNKUYU','DERİNKUYU MAL MÜDÜRLÜĞÜ'),
(758,'50','Nevşehir','GÜLŞEHİR','GÜLŞEHİR MAL MÜDÜRLÜĞÜ'),
(759,'50','Nevşehir','HACIBEKTAŞ','HACIBEKTAŞ MAL MÜDÜRLÜĞÜ'),
(760,'50','Nevşehir','KOZAKLI','KOZAKLI MAL MÜDÜRLÜĞÜ'),
(761,'50','Nevşehir','ÜRGÜP','ÜRGÜP MAL MÜDÜRLÜĞÜ'),
(762,'50','Nevşehir','ACIGÖL','ACIGÖL MAL MÜDÜRLÜĞÜ'),
(763,'50','Nevşehir','NEVŞEHİR MERKEZ','NEVŞEHİR VERGİ DAİRESİ'),
(764,'51','Niğde','ÇAMARDI','ÇAMARDI MAL MÜDÜRLÜĞÜ'),
(765,'51','Niğde','ULUKIŞLA','ULUKIŞLA MAL MÜDÜRLÜĞÜ'),
(766,'51','Niğde','ALTUNHİSAR','ALTUNHİSAR MAL MÜDÜRLÜĞÜ'),
(767,'51','Niğde','ÇİFTLİK','ÇİFTLİK MAL MÜDÜRLÜĞÜ'),
(768,'51','Niğde','NİĞDE MERKEZ','NİĞDE VERGİ DAİRESİ'),
(769,'51','Niğde','BOR','BOR VERGİ DAİRESİ'),
(770,'52','Ordu','AKKUŞ','AKKUŞ MAL MÜDÜRLÜĞÜ'),
(771,'52','Ordu','AYBASTI','AYBASTI MAL MÜDÜRLÜĞÜ'),
(772,'52','Ordu','GÖLKÖY','GÖLKÖY MAL MÜDÜRLÜĞÜ'),
(773,'52','Ordu','KORGAN','KORGAN MAL MÜDÜRLÜĞÜ'),
(774,'52','Ordu','KUMRU','KUMRU MAL MÜDÜRLÜĞÜ'),
(775,'52','Ordu','MESUDİYE','MESUDİYE MAL MÜDÜRLÜĞÜ'),
(776,'52','Ordu','PERŞEMBE','PERŞEMBE MAL MÜDÜRLÜĞÜ'),
(777,'52','Ordu','ULUBEY','ULUBEY MAL MÜDÜRLÜĞÜ'),
(778,'52','Ordu','GÜLYALI','GÜLYALI MAL MÜDÜRLÜĞÜ'),
(779,'52','Ordu','GÜRGENTEPE','GÜRGENTEPE MAL MÜDÜRLÜĞÜ'),
(780,'52','Ordu','ÇAMAŞ','ÇAMAŞ MAL MÜDÜRLÜĞÜ'),
(781,'52','Ordu','ÇATALPINAR','ÇATALPINAR MAL MÜDÜRLÜĞÜ'),
(782,'52','Ordu','ÇAYBAŞI','ÇAYBAŞI MAL MÜDÜRLÜĞÜ'),
(783,'52','Ordu','İKİZCE','İKİZCE MAL MÜDÜRLÜĞÜ'),
(784,'52','Ordu','KABADÜZ','KABADÜZ MAL MÜDÜRLÜĞÜ'),
(785,'52','Ordu','KABATAŞ','KABATAŞ MAL MÜDÜRLÜĞÜ'),
(786,'52','Ordu','BOZTEPE','BOZTEPE VERGİ DAİRESİ'),
(787,'52','Ordu','KÖPRÜBAŞI','KÖPRÜBAŞI VERGİ DAİRESİ'),
(788,'52','Ordu','FATSA','FATSA VERGİ DAİRESİ'),
(789,'52','Ordu','ÜNYE','ÜNYE VERGİ DAİRESİ'),
(790,'53','Rize','ÇAMLIHEMŞİN','ÇAMLIHEMŞİN MAL MÜDÜRLÜĞÜ'),
(791,'53','Rize','FINDIKLI','FINDIKLI MAL MÜDÜRLÜĞÜ'),
(792,'53','Rize','İKİZDERE','İKİZDERE MAL MÜDÜRLÜĞÜ'),
(793,'53','Rize','KALKANDERE','KALKANDERE MAL MÜDÜRLÜĞÜ'),
(794,'53','Rize','GÜNEYSU','GÜNEYSU MAL MÜDÜRLÜĞÜ'),
(795,'53','Rize','DEREPAZARI','DEREPAZARI MAL MÜDÜRLÜĞÜ'),
(796,'53','Rize','HEMŞİN','HEMŞİN MAL MÜDÜRLÜĞÜ'),
(797,'53','Rize','İYİDERE','İYİDERE MAL MÜDÜRLÜĞÜ'),
(798,'53','Rize','RİZE MERKEZ','KAÇKAR VERGİ DAİRESİ'),
(799,'53','Rize','RİZE MERKEZ','YEŞİLÇAY VERGİ DAİRESİ'),
(800,'53','Rize','ÇAYELİ','ÇAYELİ VERGİ DAİRESİ'),
(801,'53','Rize','PAZAR','PAZAR VERGİ DAİRESİ'),
(802,'53','Rize','ARDEŞEN','ARDEŞEN VERGİ DAİRESİ'),
(803,'54','Sakarya','KAYNARCA','KAYNARCA MAL MÜDÜRLÜĞÜ'),
(804,'54','Sakarya','KOCAALİ','KOCAALİ MAL MÜDÜRLÜĞÜ'),
(805,'54','Sakarya','PAMUKOVA','PAMUKOVA MAL MÜDÜRLÜĞÜ'),
(806,'54','Sakarya','TARAKLI','TARAKLI MAL MÜDÜRLÜĞÜ'),
(807,'54','Sakarya','KARAPÜRÇEK','KARAPÜRÇEK MAL MÜDÜRLÜĞÜ'),
(808,'54','Sakarya','AKYAZI','AKYAZI VERGİ DAİRESİ'),
(809,'54','Sakarya','GEYVE','GEYVE VERGİ DAİRESİ'),
(810,'54','Sakarya','HENDEK','HENDEK VERGİ DAİRESİ'),
(811,'54','Sakarya','KARASU','KARASU VERGİ DAİRESİ'),
(812,'54','Sakarya','ADAPAZARI','SAKARYA İHTİSAS VERGİ DAİRESİ'),
(813,'54','Sakarya','SERDİVAN','GÜMRÜKÖNÜ VERGİ DAİRESİ'),
(814,'54','Sakarya','ADAPAZARI','ALİ FUAT CEBESOY VERGİ DAİRESİ'),
(815,'54','Sakarya','SAPANCA','SAPANCA VERGİ DAİRESİ'),
(816,'55','Samsun','ALAÇAM','ALAÇAM MAL MÜDÜRLÜĞÜ'),
(817,'55','Samsun','KAVAK','KAVAK MAL MÜDÜRLÜĞÜ'),
(818,'55','Samsun','LADİK','LADİK MAL MÜDÜRLÜĞÜ'),
(819,'55','Samsun','VEZİRKÖPRÜ','VEZİRKÖPRÜ MAL MÜDÜRLÜĞÜ'),
(820,'55','Samsun','ASARCIK','ASARCIK MAL MÜDÜRLÜĞÜ'),
(821,'55','Samsun','19 MAYIS','19 MAYIS MAL MÜDÜRLÜĞÜ'),
(822,'55','Samsun','SALIPAZARI','SALIPAZARI MAL MÜDÜRLÜĞÜ'),
(823,'55','Samsun','TEKKEKÖY','TEKKEKÖY MAL MÜDÜRLÜĞÜ'),
(824,'55','Samsun','AYVACIK','AYVACIK MAL MÜDÜRLÜĞÜ'),
(825,'55','Samsun','YAKAKENT','YAKAKENT MAL MÜDÜRLÜĞÜ'),
(826,'55','Samsun','BAFRA','BAFRA VERGİ DAİRESİ'),
(827,'55','Samsun','ÇARŞAMBA','ÇARŞAMBA VERGİ DAİRESİ'),
(828,'55','Samsun','TERME','TERME VERGİ DAİRESİ'),
(829,'55','Samsun','HAVZA','HAVZA VERGİ DAİRESİ'),
(830,'55','Samsun','19 MAYIS','19 MAYIS VERGİ DAİRESİ'),
(831,'55','Samsun','İLKADIM','GAZİLER VERGİ DAİRESİ'),
(832,'55','Samsun','İLKADIM','ZAFER VERGİ DAİRESİ'),
(833,'56','Siirt','BAYKAN','BAYKAN MAL MÜDÜRLÜĞÜ'),
(834,'56','Siirt','ERUH','ERUH MAL MÜDÜRLÜĞÜ'),
(835,'56','Siirt','KURTALAN','KURTALAN MAL MÜDÜRLÜĞÜ'),
(836,'56','Siirt','PERVARİ','PERVARİ MAL MÜDÜRLÜĞÜ'),
(837,'56','Siirt','ŞİRVAN','ŞİRVAN MAL MÜDÜRLÜĞÜ'),
(838,'56','Siirt','SİİRT MERKEZ','SİİRT VERGİ DAİRESİ'),
(839,'57','Sinop','AYANCIK','AYANCIK MAL MÜDÜRLÜĞÜ'),
(840,'57','Sinop','DURAĞAN','DURAĞAN MAL MÜDÜRLÜĞÜ'),
(841,'57','Sinop','ERFELEK','ERFELEK MAL MÜDÜRLÜĞÜ'),
(842,'57','Sinop','GERZE','GERZE MAL MÜDÜRLÜĞÜ'),
(843,'57','Sinop','TÜRKELİ','TÜRKELİ MAL MÜDÜRLÜĞÜ'),
(844,'57','Sinop','DİKMEN','DİKMEN MAL MÜDÜRLÜĞÜ'),
(845,'57','Sinop','SARAYDÜZÜ','SARAYDÜZÜ MAL MÜDÜRLÜĞÜ'),
(846,'57','Sinop','SİNOP MERKEZ','SİNOP VERGİ DAİRESİ'),
(847,'57','Sinop','BOYABAT','BOYABAT VERGİ DAİRESİ'),
(848,'58','Sivas','DİVRİĞİ','DİVRİĞİ MAL MÜDÜRLÜĞÜ'),
(849,'58','Sivas','GEMEREK','GEMEREK MAL MÜDÜRLÜĞÜ'),
(850,'58','Sivas','GÜRÜN','GÜRÜN MAL MÜDÜRLÜĞÜ'),
(851,'58','Sivas','HAFİK','HAFİK MAL MÜDÜRLÜĞÜ'),
(852,'58','Sivas','İMRANLI','İMRANLI MAL MÜDÜRLÜĞÜ'),
(853,'58','Sivas','KANGAL','KANGAL MAL MÜDÜRLÜĞÜ'),
(854,'58','Sivas','KOYULHİSAR','KOYULHİSAR MAL MÜDÜRLÜĞÜ'),
(855,'58','Sivas','SUŞEHRİ','SUŞEHRİ MAL MÜDÜRLÜĞÜ'),
(856,'58','Sivas','YILDIZELİ','YILDIZELİ MAL MÜDÜRLÜĞÜ'),
(857,'58','Sivas','ZARA','ZARA MAL MÜDÜRLÜĞÜ'),
(858,'58','Sivas','AKINCILAR','AKINCILAR MAL MÜDÜRLÜĞÜ'),
(859,'58','Sivas','ALTINYAYLA','ALTINYAYLA MAL MÜDÜRLÜĞÜ'),
(860,'58','Sivas','DOĞANŞAR','DOĞANŞAR MAL MÜDÜRLÜĞÜ'),
(861,'58','Sivas','GÖLOVA','GÖLOVA MAL MÜDÜRLÜĞÜ'),
(862,'58','Sivas','ULAŞ','ULAŞ MAL MÜDÜRLÜĞÜ'),
(863,'58','Sivas','KALE','KALE VERGİ DAİRESİ'),
(864,'58','Sivas','ŞARKIŞLA','ŞARKIŞLA VERGİ DAİRESİ'),
(865,'58','Sivas','SİVAS MERKEZ','SİTE VERGİ DAİRESİ'),
(866,'59','Tekirdağ','SARAY','SARAY MAL MÜDÜRLÜĞÜ'),
(867,'59','Tekirdağ','MARMARAEREĞLİSİ','MARM. EREĞLİSİ MAL MÜDÜRLÜĞÜ'),
(868,'59','Tekirdağ','SÜLEYMANPAŞA','SÜLEYMANPAŞA VERGİ DAİRESİ'),
(869,'59','Tekirdağ','ÇORLU','ÇORLU İHTİSAS VERGİ DAİRESİ'),
(870,'59','Tekirdağ','SÜLEYMANPAŞA','NAMIK KEMAL VERGİ DAİRESİ'),
(871,'59','Tekirdağ','ÇERKEZKÖY','ÇERKEZKÖY VERGİ DAİRESİ'),
(872,'59','Tekirdağ','ÇORLU','ÇORLU VERGİ DAİRESİ'),
(873,'59','Tekirdağ','HAYRABOLU','HAYRABOLU VERGİ DAİRESİ'),
(874,'59','Tekirdağ','MALKARA','MALKARA VERGİ DAİRESİ'),
(875,'59','Tekirdağ','MURATLI','MURATLI VERGİ DAİRESİ'),
(876,'59','Tekirdağ','ŞARKÖY','ŞARKÖY VERGİ DAİRESİ'),
(877,'59','Tekirdağ','KAPAKLI','KAPAKLI VERGİ DAİRESİ'),
(878,'60','Tokat','ALMUS','ALMUS MAL MÜDÜRLÜĞÜ'),
(879,'60','Tokat','ARTOVA','ARTOVA MAL MÜDÜRLÜĞÜ'),
(880,'60','Tokat','REŞADİYE','REŞADİYE MAL MÜDÜRLÜĞÜ'),
(881,'60','Tokat','PAZAR','PAZAR MAL MÜDÜRLÜĞÜ'),
(882,'60','Tokat','YEŞİLYURT','YEŞİLYURT MAL MÜDÜRLÜĞÜ'),
(883,'60','Tokat','BAŞÇİFTLİK','BAŞÇİFTLİK MAL MÜDÜRLÜĞÜ'),
(884,'60','Tokat','SULUSARAY','SULUSARAY MAL MÜDÜRLÜĞÜ'),
(885,'60','Tokat','TOKAT MERKEZ','TOKAT VERGİ DAİRESİ'),
(886,'60','Tokat','ERBAA','ERBAA VERGİ DAİRESİ'),
(887,'60','Tokat','NİKSAR','NİKSAR VERGİ DAİRESİ'),
(888,'60','Tokat','TURHAL','TURHAL VERGİ DAİRESİ'),
(889,'60','Tokat','ZİLE','ZİLE VERGİ DAİRESİ'),
(890,'61','Trabzon','ARAKLI','ARAKLI MAL MÜDÜRLÜĞÜ'),
(891,'61','Trabzon','ARSİN','ARSİN MAL MÜDÜRLÜĞÜ'),
(892,'61','Trabzon','ÇAYKARA','ÇAYKARA MAL MÜDÜRLÜĞÜ'),
(893,'61','Trabzon','MAÇKA','MAÇKA MAL MÜDÜRLÜĞÜ'),
(894,'61','Trabzon','SÜRMENE','SÜRMENE MAL MÜDÜRLÜĞÜ'),
(895,'61','Trabzon','TONYA','TONYA MAL MÜDÜRLÜĞÜ'),
(896,'61','Trabzon','YOMRA','YOMRA MAL MÜDÜRLÜĞÜ'),
(897,'61','Trabzon','BEŞİKDÜZÜ','BEŞİKDÜZÜ MAL MÜDÜRLÜĞÜ'),
(898,'61','Trabzon','ŞALPAZARI','ŞALPAZARI MAL MÜDÜRLÜĞÜ'),
(899,'61','Trabzon','ÇARŞIBAŞI','ÇARŞIBAŞI MAL MÜDÜRLÜĞÜ'),
(900,'61','Trabzon','DERNEKPAZARI','DERNEKPAZARI MAL MÜDÜRLÜĞÜ'),
(901,'61','Trabzon','DÜZKÖY','DÜZKÖY MAL MÜDÜRLÜĞÜ'),
(902,'61','Trabzon','HAYRAT','HAYRAT MAL MÜDÜRLÜĞÜ'),
(903,'61','Trabzon','KÖPRÜBAŞI','KÖPRÜBAŞI MAL MÜDÜRLÜĞÜ'),
(904,'61','Trabzon','TRABZON MERKEZ','HIZIRBEY VERGİ DAİRESİ'),
(905,'61','Trabzon','AKÇAABAT','AKÇAABAT VERGİ DAİRESİ'),
(906,'61','Trabzon','OF','OF VERGİ DAİRESİ'),
(907,'61','Trabzon','VAKFIKEBİR','VAKFIKEBİR VERGİ DAİRESİ'),
(908,'61','Trabzon','ORTAHİSAR','KARADENİZ VERGİ DAİRESİ'),
(909,'62','Tunceli','ÇEMİŞGEZEK','ÇEMİŞGEZEK MAL MÜDÜRLÜĞÜ'),
(910,'62','Tunceli','HOZAT','HOZAT MAL MÜDÜRLÜĞÜ'),
(911,'62','Tunceli','MAZGİRT','MAZGİRT MAL MÜDÜRLÜĞÜ'),
(912,'62','Tunceli','NAZİMİYE','NAZİMİYE MAL MÜDÜRLÜĞÜ'),
(913,'62','Tunceli','OVACIK','OVACIK MAL MÜDÜRLÜĞÜ'),
(914,'62','Tunceli','PERTEK','PERTEK MAL MÜDÜRLÜĞÜ'),
(915,'62','Tunceli','PÜLÜMÜR','PÜLÜMÜR MAL MÜDÜRLÜĞÜ'),
(916,'62','Tunceli','TUNCELİ MERKEZ','TUNCELİ VERGİ DAİRESİ'),
(917,'63','Şanlıurfa','AKÇAKALE','AKÇAKALE MAL MÜDÜRLÜĞÜ'),
(918,'63','Şanlıurfa','BOZOVA','BOZOVA MAL MÜDÜRLÜĞÜ'),
(919,'63','Şanlıurfa','HALFETİ','HALFETİ MAL MÜDÜRLÜĞÜ'),
(920,'63','Şanlıurfa','HİLVAN','HİLVAN MAL MÜDÜRLÜĞÜ'),
(921,'63','Şanlıurfa','CEYLANPINAR','CEYLANPINAR MAL MÜDÜRLÜĞÜ'),
(922,'63','Şanlıurfa','HARRAN','HARRAN MAL MÜDÜRLÜĞÜ'),
(923,'63','Şanlıurfa','HALİLİYE','ŞEHİTLİK VERGİ DAİRESİ'),
(924,'63','Şanlıurfa','SİVEREK','SİVEREK VERGİ DAİRESİ'),
(925,'63','Şanlıurfa','VİRANŞEHİR','VİRANŞEHİR VERGİ DAİRESİ'),
(926,'63','Şanlıurfa','BİRECİK','BİRECİK VERGİ DAİRESİ'),
(927,'63','Şanlıurfa','SURUÇ','SURUÇ VERGİ DAİRESİ'),
(928,'63','Şanlıurfa','HALİLİYE','TOPÇUMEYDANI VERGİ DAİRESİ'),
(929,'63','Şanlıurfa','HALİLİYE','GÖBEKLİTEPE VERGİ DAİRESİ'),
(930,'64','Uşak','KARAHALLI','KARAHALLI MAL MÜDÜRLÜĞÜ'),
(931,'64','Uşak','ULUBEY','ULUBEY MAL MÜDÜRLÜĞÜ'),
(932,'64','Uşak','SİVASLI','SİVASLI MAL MÜDÜRLÜĞÜ'),
(933,'64','Uşak','UŞAK MERKEZ','UŞAK VERGİ DAİRESİ'),
(934,'64','Uşak','BANAZ','BANAZ VERGİ DAİRESİ'),
(935,'64','Uşak','EŞME','EŞME VERGİ DAİRESİ'),
(936,'65','Van','BAŞKALE','BAŞKALE MAL MÜDÜRLÜĞÜ'),
(937,'65','Van','ÇATAK','ÇATAK MAL MÜDÜRLÜĞÜ'),
(938,'65','Van','GEVAŞ','GEVAŞ MAL MÜDÜRLÜĞÜ'),
(939,'65','Van','GÜRPINAR','GÜRPINAR MAL MÜDÜRLÜĞÜ'),
(940,'65','Van','MURADİYE','MURADİYE MAL MÜDÜRLÜĞÜ'),
(941,'65','Van','ÖZALP','ÖZALP MAL MÜDÜRLÜĞÜ'),
(942,'65','Van','BAHÇESARAY','BAHÇESARAY MAL MÜDÜRLÜĞÜ'),
(943,'65','Van','ÇALDIRAN','ÇALDIRAN MAL MÜDÜRLÜĞÜ'),
(944,'65','Van','EDREMİT','EDREMİT MAL MÜDÜRLÜĞÜ'),
(945,'65','Van','SARAY','SARAY MAL MÜDÜRLÜĞÜ'),
(946,'65','Van','ERCİŞ','ERCİŞ VERGİ DAİRESİ'),
(947,'65','Van','VAN MERKEZ','VAN VERGİ DAİRESİ'),
(948,'66','Yozgat','AKDAĞMADENİ','AKDAĞMADENİ MAL MÜDÜRLÜĞÜ'),
(949,'66','Yozgat','ÇAYIRALAN','ÇAYIRALAN MAL MÜDÜRLÜĞÜ'),
(950,'66','Yozgat','ÇEKEREK','ÇEKEREK MAL MÜDÜRLÜĞÜ'),
(951,'66','Yozgat','SARIKAYA','SARIKAYA MAL MÜDÜRLÜĞÜ'),
(952,'66','Yozgat','ŞEFAATLİ','ŞEFAATLİ MAL MÜDÜRLÜĞÜ'),
(953,'66','Yozgat','AYDINCIK','AYDINCIK MAL MÜDÜRLÜĞÜ'),
(954,'66','Yozgat','ÇANDIR','ÇANDIR MAL MÜDÜRLÜĞÜ'),
(955,'66','Yozgat','KADIŞEHRİ','KADIŞEHRİ MAL MÜDÜRLÜĞÜ'),
(956,'66','Yozgat','SARAYKENT','SARAYKENT MAL MÜDÜRLÜĞÜ'),
(957,'66','Yozgat','YENİFAKILI','YENİFAKILI MAL MÜDÜRLÜĞÜ'),
(958,'66','Yozgat','YOZGAT MERKEZ','YOZGAT VERGİ DAİRESİ'),
(959,'66','Yozgat','BOĞAZLIYAN','BOĞAZLIYAN VERGİ DAİRESİ'),
(960,'66','Yozgat','SORGUN','SORGUN VERGİ DAİRESİ'),
(961,'66','Yozgat','YERKÖY','YERKÖY VERGİ DAİRESİ'),
(962,'67','Zonguldak','ALAPLI','ALAPLI MAL MÜDÜRLÜĞÜ'),
(963,'67','Zonguldak','GÖKÇEBEY','GÖKÇEBEY MAL MÜDÜRLÜĞÜ'),
(964,'67','Zonguldak','ZONGULDAK MERKEZ','UZUNMEHMET VERGİ DAİRESİ'),
(965,'67','Zonguldak','EREĞLİ','KARADENİZ EREĞLİ VERGİ DAİRESİ'),
(966,'67','Zonguldak','ÇAYCUMA','ÇAYCUMA VERGİ DAİRESİ'),
(967,'67','Zonguldak','DEVREK','DEVREK VERGİ DAİRESİ'),
(968,'67','Zonguldak','ZONGULDAK MERKEZ','KARAELMAS VERGİ DAİRESİ'),
(969,'68','Aksaray','AĞAÇÖREN','AĞAÇÖREN MAL MÜDÜRLÜĞÜ'),
(970,'68','Aksaray','GÜZELYURT','GÜZELYURT MAL MÜDÜRLÜĞÜ'),
(971,'68','Aksaray','ORTAKÖY','ORTAKÖY MAL MÜDÜRLÜĞÜ'),
(972,'68','Aksaray','SARIYAHŞİ','SARIYAHŞİ MAL MÜDÜRLÜĞÜ'),
(973,'68','Aksaray','ESKİL','ESKİL MAL MÜDÜRLÜĞÜ'),
(974,'68','Aksaray','GÜLAĞAÇ','GÜLAĞAÇ MAL MÜDÜRLÜĞÜ'),
(975,'68','Aksaray','SULTANHANI','SULTANHANI MAL MÜDÜRLÜĞÜ'),
(976,'68','Aksaray','AKSARAY MERKEZ','AKSARAY VERGİ DAİRESİ'),
(977,'69','Bayburt','AYDINTEPE','AYDINTEPE MAL MÜDÜRLÜĞÜ'),
(978,'69','Bayburt','DEMİRÖZÜ','DEMİRÖZÜ MAL MÜDÜRLÜĞÜ'),
(979,'69','Bayburt','BAYBURT MERKEZ','BAYBURT VERGİ DAİRESİ'),
(980,'70','Karaman','AYRANCI','AYRANCI MAL MÜDÜRLÜĞÜ'),
(981,'70','Karaman','ERMENEK','ERMENEK MAL MÜDÜRLÜĞÜ'),
(982,'70','Karaman','KAZIMKARABEKİR','K.KARABEKİR MAL MÜDÜRLÜĞÜ'),
(983,'70','Karaman','BAŞYAYLA','BAŞYAYLA MAL MÜDÜRLÜĞÜ'),
(984,'70','Karaman','SARIVELİLER','SARIVELİLER MAL MÜDÜRLÜĞÜ'),
(985,'70','Karaman','KARAMAN MERKEZ','KARAMAN VERGİ DAİRESİ'),
(986,'71','Kırıkkale','DELİCE','DELİCE MAL MÜDÜRLÜĞÜ'),
(987,'71','Kırıkkale','KESKİN','KESKİN MAL MÜDÜRLÜĞÜ'),
(988,'71','Kırıkkale','SULAKYURT','SULAKYURT MAL MÜDÜRLÜĞÜ'),
(989,'71','Kırıkkale','BALIŞEYH','BALIŞEYH MAL MÜDÜRLÜĞÜ'),
(990,'71','Kırıkkale','ÇELEBİ','ÇELEBİ MAL MÜDÜRLÜĞÜ'),
(991,'71','Kırıkkale','KARAKEÇİLİ','KARAKEÇİLİ MAL MÜDÜRLÜĞÜ'),
(992,'71','Kırıkkale','KIRIKKALE MERKEZ','IRMAK VERGİ DAİRESİ'),
(993,'71','Kırıkkale','KIRIKKALE MERKEZ','KALETEPE VERGİ DAİRESİ'),
(994,'72','Batman','BEŞİRİ','BEŞİRİ MAL MÜDÜRLÜĞÜ'),
(995,'72','Batman','GERCÜŞ','GERCÜŞ MAL MÜDÜRLÜĞÜ'),
(996,'72','Batman','HASANKEYF','HASANKEYF MAL MÜDÜRLÜĞÜ'),
(997,'72','Batman','KOZLUK','KOZLUK MAL MÜDÜRLÜĞÜ'),
(998,'72','Batman','SASON','SASON MAL MÜDÜRLÜĞÜ'),
(999,'72','Batman','BATMAN MERKEZ','BATMAN VERGİ DAİRESİ'),
(1000,'73','Şırnak','BEYTÜŞŞEBAP','BEYTÜŞŞEBAP MAL MÜDÜRLÜĞÜ'),
(1001,'73','Şırnak','GÜÇLÜKONAK','GÜÇLÜKONAK MAL MÜDÜRLÜĞÜ'),
(1002,'73','Şırnak','İDİL','İDİL MAL MÜDÜRLÜĞÜ'),
(1003,'73','Şırnak','ULUDERE','ULUDERE MAL MÜDÜRLÜĞÜ'),
(1004,'73','Şırnak','ŞIRNAK MERKEZ','ŞIRNAK VERGİ DAİRESİ'),
(1005,'73','Şırnak','CİZRE','CİZRE VERGİ DAİRESİ'),
(1006,'73','Şırnak','SİLOPİ','SİLOPİ VERGİ DAİRESİ'),
(1007,'74','Bartın','AMASRA','AMASRA MAL MÜDÜRLÜĞÜ'),
(1008,'74','Bartın','KURUCAŞİLE','KURUCAŞİLE MAL MÜDÜRLÜĞÜ'),
(1009,'74','Bartın','ULUS','ULUS MAL MÜDÜRLÜĞÜ'),
(1010,'74','Bartın','BARTIN MERKEZ','BARTIN VERGİ DAİRESİ'),
(1011,'75','Ardahan','ÇILDIR','ÇILDIR MAL MÜDÜRLÜĞÜ'),
(1012,'75','Ardahan','DAMAL','DAMAL MAL MÜDÜRLÜĞÜ'),
(1013,'75','Ardahan','GÖLE','GÖLE MAL MÜDÜRLÜĞÜ'),
(1014,'75','Ardahan','HANAK','HANAK MAL MÜDÜRLÜĞÜ'),
(1015,'75','Ardahan','POSOF','POSOF MAL MÜDÜRLÜĞÜ'),
(1016,'75','Ardahan','ARDAHAN MERKEZ','ARDAHAN VERGİ DAİRESİ'),
(1017,'76','Iğdır','ARALIK','ARALIK MAL MÜDÜRLÜĞÜ'),
(1018,'76','Iğdır','KARAKOYUNLU','KARAKOYUNLU MAL MÜDÜRLÜĞÜ'),
(1019,'76','Iğdır','TUZLUCA','TUZLUCA MAL MÜDÜRLÜĞÜ'),
(1020,'76','Iğdır','IĞDIR MERKEZ','IĞDIR VERGİ DAİRESİ'),
(1021,'77','Yalova','ALTINOVA','ALTINOVA MAL MÜDÜRLÜĞÜ'),
(1022,'77','Yalova','ARMUTLU','ARMUTLU MAL MÜDÜRLÜĞÜ'),
(1023,'77','Yalova','ÇINARCIK','ÇINARCIK MAL MÜDÜRLÜĞÜ'),
(1024,'77','Yalova','YALOVA MERKEZ','YALOVA VERGİ DAİRESİ'),
(1025,'78','Karabük','EFLANİ','EFLANİ MAL MÜDÜRLÜĞÜ'),
(1026,'78','Karabük','ESKİPAZAR','ESKİPAZAR MAL MÜDÜRLÜĞÜ'),
(1027,'78','Karabük','OVACIK','OVACIK MAL MÜDÜRLÜĞÜ'),
(1028,'78','Karabük','YENİCE','YENİCE MAL MÜDÜRLÜĞÜ'),
(1029,'78','Karabük','KARABÜK MERKEZ','KARABÜK VERGİ DAİRESİ'),
(1030,'78','Karabük','SAFRANBOLU','SAFRANBOLU VERGİ DAİRESİ'),
(1031,'79','Kilis','KİLİS MERKEZ','KİLİS VERGİ DAİRESİ'),
(1032,'80','Osmaniye','BAHÇE','BAHÇE MAL MÜDÜRLÜĞÜ'),
(1033,'80','Osmaniye','DÜZİÇİ','DÜZİÇİ MAL MÜDÜRLÜĞÜ'),
(1034,'80','Osmaniye','HASANBEYLİ','HASANBEYLİ MAL MÜDÜRLÜĞÜ'),
(1035,'80','Osmaniye','SUMBAS','SUMBAS MAL MÜDÜRLÜĞÜ'),
(1036,'80','Osmaniye','TOPRAKKALE','TOPRAKKALE MAL MÜDÜRLÜĞÜ'),
(1037,'80','Osmaniye','OSMANİYE MERKEZ','OSMANİYE VERGİ DAİRESİ'),
(1038,'80','Osmaniye','KADİRLİ','KADİRLİ VERGİ DAİRESİ'),
(1039,'81','Düzce','CUMAYERİ','CUMAYERİ MAL MÜDÜRLÜĞÜ'),
(1040,'81','Düzce','ÇİLİMLİ','ÇİLİMLİ MAL MÜDÜRLÜĞÜ'),
(1041,'81','Düzce','GÖLYAKA','GÖLYAKA MAL MÜDÜRLÜĞÜ'),
(1042,'81','Düzce','GÜMÜŞOVA','GÜMÜŞOVA MAL MÜDÜRLÜĞÜ'),
(1043,'81','Düzce','KAYNAŞLI','KAYNAŞLI MAL MÜDÜRLÜĞÜ'),
(1044,'81','Düzce','YIĞILCA','YIĞILCA MAL MÜDÜRLÜĞÜ'),
(1045,'81','Düzce','DÜZCE MERKEZ','DÜZCE VERGİ DAİRESİ'),
(1046,'81','Düzce','AKÇAKOCA','AKÇAKOCA VERGİ DAİRESİ');


UNLOCK TABLES;

